/**
 * Part C: Explain one [2] and Define with example [2]
 * MS: 1 mark identification/definition + 1 mark explanation/example
 * Each question has multiple pathways (ans = array of [id, expl] pairs).
 * Identification from source for Section A Q1(c). Explanation mark can be given even without identification.
 * Sources: 0455/22 O/N 2023 (Honduras) EXACT; 0455 specimen 2020; w23/23 Montenegro, s22/21 Cyprus,
 *   w24/21 UAE, s24/21 Nicaragua, s23/21 Australia, s22/22 Bhutan, m23/22 US, s20/21 Vietnam,
 *   w21/21 Laos, s22/23 Malta, s24/22 Tunisia. Full syllabus coverage.
 */
const partCData = [
  /* === EXACT from 0455/22 O/N 2023 (Honduras) 1(c) === */
  { "id": "2281_1c_01", "case": "Honduras used to concentrate on growing bananas and coffee, gaining skills and a good reputation in those industries. Now, Honduras produces a greater range of products including clothes, chemicals and paper.", "q": "Explain one advantage of an economy specialising.", "ans": [["Gain skills", "raise productivity / raise efficiency / practice makes perfect / lower costs of production / raise quality / increase output / supply / less waste / more productive / more efficient"], ["Gain a good reputation", "increase demand / more exports / higher sales"]], "concept": "0455/22 O/N 2023 (Honduras) 1(c) EXACT. MS: Gain skills (1)+expl OR Gain reputation (1)+expl. Identification from source." },
  /* --- Honduras 1(d) adapted to Explain one (same extract) --- */
  { "id": "2281_1c_02", "case": "The Honduran government tries to reduce poverty by, for example, providing unemployment benefit. The country has a progressive income tax system, so there could be a significant rise in tax revenue.", "q": "Explain one way a government could redistribute income.", "ans": [["Unemployment benefit / state benefit / welfare benefit", "raise income of those on low or no income / reduce poverty / support needy / enable unemployed to buy necessities"], ["Progressive income tax / progressive tax system", "takes higher proportion from the rich / helps those on low incomes / wealthier pay more"]], "concept": "0455/22 O/N 2023 (Honduras) 1(d) adapted to Explain one. Identification from source." },
  { "id": "2281_1c_03", "case": "Botswana had a low inflation rate between 2015 and 2019. The country moved towards free trade.", "q": "Explain one reason why a low inflation rate may increase economic growth.", "ans": [["International competitiveness / competitiveness / competitive", "sell more exports / buy fewer imports / cheaper exports"], ["Greater certainty / stability / predictable", "encourage investment / attract firms / business confidence"]], "concept": "Low inflation keeps prices competitive; certainty encourages investment." },
  { "id": "2281_1c_04", "case": "Firms in Suriname could not cover their variable costs and some fixed costs. Output fell and unemployment rose.", "q": "Explain one type of unemployment.", "ans": [["Cyclical / demand-deficient / cyclical unemployment", "lack of total demand / occurs during recession / downturn / falling demand"]], "concept": "Cyclical: falls in total demand." },
  { "id": "2281_1c_05", "case": "In 2022, the number of job vacancies in the technology sector in Malaysia reached 50,000, while many high school leavers without coding or digital skills remained out of work for over six months. Industry groups have called for more vocational training.", "q": "Explain one type of unemployment.", "ans": [["Structural unemployment / structural", "skills not matching vacancies / change in demand for labour / labor / skill mismatch"]], "concept": "Structural: mismatch of skills." },
  { "id": "2281_1c_06", "case": "Labour market surveys in New Zealand showed that around 3% of the workforce was temporarily out of work in the first quarter of 2023, often because they had left one job and were still searching for a suitable new role. The average job-search period was six weeks.", "q": "Explain one type of unemployment.", "ans": [["Frictional unemployment / frictional", "workers in between jobs / searching for work / short term / job search"]], "concept": "Frictional: short-term between jobs." },
  { "id": "2281_1c_07", "case": "The government of Thailand introduced subsidies of 200 baht per tonne for rice farmers in 2021 to support rural incomes. Rice is a staple food and consumption changes little when its price rises. Many smallholders rely on rice sales for their livelihood.", "q": "Explain one reason why a government may subsidise food production.", "ans": [["Reduce price / help consumers / lower price", "make food more affordable / reduce poverty / cheaper for consumers"]], "concept": "1 mark: reason. 1 mark: effect." },
  { "id": "2281_1c_08", "case": "Singapore decreased its population and labour force. Some markets moved from disequilibrium to equilibrium.", "q": "Explain how a market moves from disequilibrium to equilibrium.", "ans": [["If demand exceeds supply there is shortage", "price rises until equilibrium / price increases"], ["If supply exceeds demand there is surplus", "price falls until equilibrium / price decreases"]], "concept": "Shortage → price rises. Surplus → price falls." },
  { "id": "2281_1c_09", "case": "Inflation rose because trade unions negotiated a 10% pay rise and the global price of electricity spiked.", "q": "Explain one cause of inflation.", "ans": [["Cost-push inflation / cost push", "rise in costs of production / wages / raw materials / labour / labor / electricity / energy / input costs / input prices"]], "concept": "Cost-push: costs push prices up." },
  { "id": "2281_1c_10", "case": "Vietnam's GDP grew by 7% in 2022. Unemployment fell to 2.3% and real wages rose. Retail sales increased by 20% compared with the previous year. Consumer confidence reached a ten-year high.", "q": "Explain one cause of inflation.", "ans": [["Demand-pull inflation / demand pull", "total demand exceeds supply / increased consumer spending / too much demand"]], "concept": "Demand-pull: too much demand." },
  { "id": "2281_1c_11", "case": "Local councils in the UK fund street lighting from taxes. Once the lights are installed, it is not possible to prevent households who did not pay from benefiting. Similarly, one driver's use of the lit road does not reduce the light available to others.", "q": "Explain one characteristic of public goods.", "ans": [["Non-excludability / non excludability", "cannot stop non-payers from using / exclude people / free riders"], ["Non-rivalry / non rivalry", "one person's use does not reduce another's / consumption does not reduce availability"]], "concept": "Non-excludability = can't exclude. Non-rivalry = no rivalry in use." },
  { "id": "2281_1c_12", "case": "Following the merger of two major airlines in 2019, the combined company reduced the number of flights on regional routes by 15%. Average ticket prices on those routes increased by 22% over the following year, according to industry data.", "q": "Explain one disadvantage of a monopoly.", "ans": [["Higher prices / increased prices", "lack of competition allows firm to charge more / no competition"], ["Reduced choice / less supply / fewer options", "fewer options for consumers / less variety / limited choice"]], "concept": "Monopoly can exploit market power; reduces consumer choice." },
  { "id": "2281_1c_13", "case": "A car factory in Germany introduced an assembly line where each worker performs a single task, such as fitting doors or installing wiring. Output per worker rose by 35% in the first year, and the time taken to produce each car fell from 12 hours to 8 hours.", "q": "Explain one advantage of division of labour.", "ans": [["Specialisation / specialization", "higher output / efficiency / speed / productivity"]], "concept": "Specialisation increases productivity." },
  { "id": "2281_1c_14", "case": "A survey of workers in a smartphone assembly plant found that 60% reported boredom and low job satisfaction. Most employees performed the same narrow task, such as attaching a single component, for the whole shift. Absenteeism in the plant was above the industry average.", "q": "Explain one disadvantage of specialisation for workers.", "ans": [["Job dissatisfaction / boredom", "lower productivity / demotivation / repetitive work"]], "concept": "Repetition can reduce motivation." },
  { "id": "2281_1c_15", "case": "The central bank made it cheaper for banks to borrow. It sold government debt.", "q": "Explain one monetary policy tool.", "ans": [["Interest rates / discount rate / base rate", "lower rates encourage borrowing / spending / cheaper to borrow"], ["Open market operations / OMO", "selling bonds reduces money supply / buying bonds increases it"]], "concept": "Interest rate affects cost of borrowing; OMO: buying/selling govt bonds." },
  { "id": "2281_1c_16", "case": "In March 2023, the central bank of Turkey sold $2.5 billion of government bonds it had been holding. The move was intended to reduce the amount of money in circulation. Commercial bank lending had grown by 45% over the previous twelve months.", "q": "Explain one monetary policy tool.", "ans": [["Open market operations / OMO", "selling bonds reduces money supply / buying bonds increases it"]], "concept": "OMO: buying/selling govt bonds." },
  { "id": "2281_1c_17", "case": "The government of India announced in 2021 that it would sell its 100% stake in the national airline and scrap the minimum fare rules that had been in place on domestic routes since 1997. The aviation minister stated that the aim was to increase competition and efficiency in the sector.", "q": "Explain one supply-side policy measure.", "ans": [["Privatisation / privatization", "increase efficiency / competition / sell state assets"], ["Deregulation", "increase competition / remove restrictions / fewer rules"]], "concept": "Privatisation = selling state assets. Deregulation = removing rules." },
  { "id": "2281_1c_18", "case": "In 2015, the UK raised the compulsory education age to 18. Students must now remain in full-time education, an apprenticeship, or training until that age. The government argued that a better-educated workforce would boost productivity and help the economy compete internationally.", "q": "Explain one supply-side policy measure.", "ans": [["Education / training", "improve skills / labour quality / labor quality / productivity / human capital"]], "concept": "Education improves human capital." },
  { "id": "2281_1c_19", "case": "When the Nigerian naira lost 40% of its value against the US dollar between 2020 and 2021, Nigerian cocoa and textile exporters reported a sharp rise in orders from Europe. At the same time, the cost of imported machinery and fertiliser increased substantially for domestic firms.", "q": "Explain one effect of currency depreciation.", "ans": [["Exports become cheaper / more competitive", "increase export demand / sales / more exports"], ["Imports become more expensive / costly imports", "higher costs for imported goods / import prices rise"]], "concept": "Depreciation = weaker currency." },
  { "id": "2281_1c_20", "case": "A South Korean electronics company opened a new plant in Bangladesh in 2022, employing 2,400 local workers. The firm ran a six-month training programme in assembly and quality control. Local engineers were also sent to the company's headquarters for technical training. The construction of the factory, however, required the clearing of a historic village site.", "q": "Explain one benefit of foreign investment.", "ans": [["Training / jobs / employment", "increase skills / employment / transfer technology"]], "concept": "MNCs can transfer skills." },
  { "id": "2281_1c_21", "case": "In 2019, the EU imposed tariffs on steel imports from China after an investigation found that Chinese producers were selling certain steel products at prices below their cost of production. The EU argued that this was harming its own steel industry and threatening thousands of jobs.", "q": "Explain one reason for protection.", "ans": [["Prevent dumping / anti-dumping", "protect domestic firms / jobs from unfair competition"]], "concept": "Dumping = selling below cost." },
  { "id": "2281_1c_22", "case": "The government of Ethiopia has protected its infant leather and garment industries with tariffs of up to 35% on imported goods. Officials argue that domestic firms need time to build scale and develop skills before they can compete with established producers in Asia.", "q": "Explain one reason for protection.", "ans": [["Infant industry argument / infant industries", "new firms need time to grow / develop / establish"]], "concept": "Infant = new, need protection." },

  /* --- Define, with an example [2] - Section B style --- */
  { "id": "2281_1c_23", "case": "Botswana uses both capital goods and labour in diamond mining.", "q": "Define, with an example, a capital good.", "ans": [["A good used to produce another good or service", "e.g. machine / equipment / factory / machinery / tools"]], "concept": "1 mark: definition. 1 mark: example." },
  { "id": "2281_1c_24", "case": "During the Covid-19 lockdown in 2020, many factories in Pakistan closed temporarily. Despite producing nothing, firms still had to pay lease payments on their premises, interest on loans, and salaries for managers. Variable costs such as raw materials and overtime wages fell to zero.", "q": "Define, with an example, a fixed cost.", "ans": [["A cost that does not change with output / paid when output is zero", "e.g. rent / interest / lease / salary"]], "concept": "FC: doesn't vary with output." },
  { "id": "2281_1c_25", "case": "Emu meat producers in Australia can expand production quickly when prices rise. Farms have spare capacity and breeding stock can be brought into production within months. When prices increased by 10% in 2022, supply rose by 25% within a year.", "q": "Define elastic supply.", "ans": [["Percentage change in quantity supplied greater than percentage change in price", "PES greater than one / responsive to price"]], "concept": "Elastic = responsive to price." },
  { "id": "2281_1c_26", "case": "A farmer in Argentina has 100 hectares of land suitable for wheat or maize. In 2023, he chose to plant wheat and harvested 4,000 tonnes. The same land could have produced 5,000 tonnes of maize. The maize output was the sacrifice involved in his decision.", "q": "Define opportunity cost.", "ans": [["The next best alternative given up", "value of the next best option forgone / sacrifice"]], "concept": "What you give up when choosing." },
  { "id": "2281_1c_27", "case": "A study of smartphone sales in India found that when prices fell by 15% in 2021, the quantity purchased increased by 28%. Retailers reported that consumers were prepared to buy more units at lower price points, especially during festival promotions.", "q": "Define demand.", "ans": [["Quantity consumers are willing and able to buy at each price", "amount purchased at different prices / quantity demanded"]], "concept": "Demand = W&A at each price." },
  { "id": "2281_1c_28", "case": "Labour force surveys in South Africa in 2023 showed that 7.8 million people of working age were actively looking for work but had not found employment. They had applied for jobs, registered with employment agencies, or were waiting for replies. The official unemployment rate was 32.9%.", "q": "Define unemployment.", "ans": [["People of working age without work but seeking employment", "those able and willing to work but not employed / jobless"]], "concept": "Unemployed = seeking, no job." },
  { "id": "2281_1c_29", "case": "Egypt's consumer price index rose by 33.7% in the year to September 2023. Food prices increased by 71%, and housing costs were up by 18%. The central bank described the sustained rise in the general price level as a major economic challenge.", "q": "Define inflation.", "ans": [["Sustained rise in the average price level", "general increase in prices over time / rising prices"]], "concept": "Inflation = rising price level." },
  { "id": "2281_1c_30", "case": "Nigeria's National Bureau of Statistics reported that the total value of all goods and services produced in the country in 2022 was $477 billion. This figure includes output from oil, agriculture, manufacturing, and services. It excludes intermediate goods to avoid double counting.", "q": "Define GDP.", "ans": [["Total value of goods and services produced in an economy", "output of all final goods and services / national output"]], "concept": "GDP = value of output." },
  { "id": "2281_1c_31", "case": "In 2023, the government of Indonesia raised the duty on imported vehicles from 0% to 50% for cars with engines over 1.5 litres. The tax is collected at the border when the cars enter the country. Domestic car producers welcomed the measure.", "q": "Define a tariff.", "ans": [["Tax on imports / import tax", "duty charged on imported goods"]], "concept": "Tariff = import tax." },
  { "id": "2281_1c_32", "case": "The EU's Common Agricultural Policy pays wheat farmers €63 per tonne produced. In 2022, French farmers received €2.1 billion in such payments. The policy aims to support rural incomes and ensure a stable supply of food. Farmers say the payment reduces their costs and encourages production.", "q": "Define a subsidy.", "ans": [["Payment to producers to reduce costs or encourage output", "grant / financial support to firms / government payment"]], "concept": "Subsidy = payment to producers." },
  { "id": "2281_1c_33", "case": "In Ghana, traders use the cedi to express the value of different goods. A bag of cocoa can be priced at 800 cedis and a sack of rice at 350 cedis, making it easy to compare the relative value of products and to record business transactions in a common unit.", "q": "Define one function of money.", "ans": [["Unit of account", "means of measuring or comparing value / measure prices"]], "concept": "Money functions: medium, store, unit." },
  { "id": "2281_1c_34", "case": "In rural Bangladesh, most market transactions involve banknotes. A farmer sells rice for cash and uses the same notes to buy seeds and tools. Shops accept currency in exchange for goods. Before money was widely used, people relied on barter, which was slower and less convenient.", "q": "Define one function of money.", "ans": [["Medium of exchange", "used to buy and sell goods / payment for goods"]], "concept": "Money facilitates exchange." },
  { "id": "2281_1c_35", "case": "A textile factory in Vietnam increased output from 500,000 to 800,000 shirts in 2022. Its spending on cotton, dyes, and electricity rose sharply. Overtime payments to workers also increased. The factory's lease and manager salaries, however, stayed the same.", "q": "Define, with an example, a variable cost.", "ans": [["Cost that varies with output", "e.g. raw materials / electricity / wages / labour / labor"]], "concept": "VC changes with output." },
  { "id": "2281_1c_36", "case": "The market for tomatoes in Mexico has over 50,000 producers and millions of buyers. No single farmer can influence the market price. Tomatoes from different farms are very similar, and buyers choose mainly on the basis of price. New farmers can enter the market without major barriers.", "q": "Define one characteristic of competitive markets.", "ans": [["Many buyers and sellers", "large number of firms / no single firm controls price / many competitors"]], "concept": "Competition = many firms." },
  { "id": "2281_1c_37", "case": "The national electricity supplier in Zambia is the only provider of grid power to households. There are no other firms offering the same service. The regulator has limited ability to promote competition because of the high cost of building a rival network.", "q": "Define a monopoly.", "ans": [["Single seller / sole producer in a market", "one firm dominates the market / no competition"]], "concept": "Monopoly = one seller." },
  { "id": "2281_1c_38", "case": "In 2022, Brazil exported $334 billion of goods, including soybeans, iron ore, and aircraft. It imported $271 billion of goods such as machinery, vehicles, and electronics. The difference between these two figures was positive. Trade in services is reported separately.", "q": "Define the balance of trade.", "ans": [["Difference between exports and imports of goods", "visible trade balance / trade in goods / X minus M"]], "concept": "Balance of trade = X - M goods." },
  { "id": "2281_1c_39", "case": "When the price of table salt rose by 30% in Tanzania in 2021, household purchases fell by only 4%. Salt is used in small quantities for cooking and preservation, and consumers have few alternatives. Demand for the product was relatively unresponsive to the price change.", "q": "Define price inelastic demand.", "ans": [["Percentage change in quantity demanded less than percentage change in price", "PED less than one / demand unresponsive / inelastic"]], "concept": "Inelastic = unresponsive." },
  { "id": "2281_1c_40", "case": "When average household income in Chile rose by 8% in 2021, total saving increased by 2.4%. Economists calculated that for each extra peso earned, 30 centavos were saved. The ratio of additional saving to additional income is used in models of consumer behaviour.", "q": "Define the marginal propensity to save.", "ans": [["Proportion of extra income saved", "change in saving divided by change in income / MPS"]], "concept": "MPS = ΔS / ΔY." },
  { "id": "2281_1c_41", "case": "In the UK, income tax rates rise with income. In 2023, the basic rate of 20% applied to income between £12,570 and £50,270. Earnings above that were taxed at 40%, and income over £125,140 at 45%. Higher earners therefore paid a larger share of their income in tax.", "q": "Define progressive tax.", "ans": [["Tax that takes a higher proportion from higher incomes", "rate increases as income rises / rich pay more proportion"]], "concept": "Progressive = richer pay more %." },
  { "id": "2281_1c_42", "case": "A cement plant in Egypt emits dust and fumes that drift over nearby villages. Residents report respiratory problems and damage to crops, but they do not buy cement from the plant and receive no compensation. The plant's production costs do not include the harm caused to these third parties.", "q": "Define an external cost.", "ans": [["Cost imposed on third parties not involved in the transaction", "negative effect on others not in the market / spillover cost"]], "concept": "External cost = cost to third parties." },
  { "id": "2281_1c_43", "case": "Studies in Kenya show that an extra year of schooling raises a person's earnings by about 10%, but it also reduces crime, improves public health, and makes workers more adaptable. Many families underinvest in education because they do not capture these wider benefits.", "q": "Define a merit good.", "ans": [["Good that is under-consumed / has external benefits", "social benefits exceed private benefits / positive externality"]], "concept": "Merit good = under-consumed." },
  { "id": "2281_1c_44", "case": "Japan's GDP fell by 0.9% in the fourth quarter of 2023 and by 0.8% in the first quarter of 2024. Two consecutive quarters of declining output is a common definition of a downturn. Business investment and consumer spending both weakened during this period.", "q": "Define a recession.", "ans": [["Fall in GDP / negative economic growth", "period of declining output / two quarters of negative growth / downturn"]], "concept": "Recession = falling GDP." },
  { "id": "2281_1c_45", "case": "Uganda's population has a high proportion of children under 15 (48%) and a growing number of people over 65 (2%). The working-age population (15–64) supports both groups. In 2023, there were 102 dependents for every 100 people of working age, one of the highest ratios in Africa.", "q": "Define the dependency ratio.", "ans": [["Ratio of dependents (young and elderly) to working-age population", "non-workers relative to workers / young and old per worker"]], "concept": "Dependency = young+old / working age." },
  { "id": "2281_1c_46", "case": "In 2022, several countries imposed a prohibition on imports of oil, gas, and other goods from Russia. Ships carrying Russian cargo were turned away from ports. The measure was intended to put pressure on the country's economy. No trade in the banned products was permitted.", "q": "Define an embargo.", "ans": [["Ban on imports or exports", "prohibition on trade with a country / trade ban"]], "concept": "Embargo = trade ban." },
  { "id": "2281_1c_47", "case": "Saudi Arabia keeps its currency, the riyal, at a fixed rate of 3.75 to the US dollar. The central bank buys and sells dollars to maintain this rate. If the riyal strengthens or weakens in the market, the bank intervenes so that the official rate does not change.", "q": "Define a fixed exchange rate.", "ans": [["Exchange rate set and maintained by the central bank", "rate that does not float / is pegged / managed rate"]], "concept": "Fixed = central bank sets rate." },
  { "id": "2281_1c_48", "case": "A car plant in Slovakia produced 1.2 million vehicles in 2022 with 12,000 workers. Each worker produced 100 cars per year. In 2018, with the same workforce, output was 900,000 cars. The increase in output per worker was attributed to better machinery and training.", "q": "Define productivity.", "ans": [["Output per unit of input / per worker", "efficiency / output per factor of production / output per labour / labor"]], "concept": "Productivity = output / input." },
  { "id": "2281_1c_49", "case": "In the market for maize in Malawi, the price settled at 350 kwacha per kilogram in 2023. At that price, the quantity that farmers were willing to sell matched exactly the quantity that buyers wished to purchase. There was no unsold surplus and no shortage.", "q": "Define market equilibrium.", "ans": [["When demand equals supply", "price where quantity demanded equals quantity supplied / market clearing"]], "concept": "Equilibrium = D = S." },
  { "id": "2281_1c_50", "case": "A furniture company in Poland had total revenue of 50 million zloty in 2022. Its costs for materials, wages, rent, and other expenses were 42 million zloty. The difference, 8 million zloty, was retained by the firm. Shareholders received part of this as dividends.", "q": "Define profit.", "ans": [["Total revenue minus total cost", "difference between income from sales and costs / TR minus TC"]], "concept": "Profit = TR - TC." },
  { "id": "2281_1c_51", "case": "The World Bank defines the international poverty line at $2.15 per day (2017 prices). In 2021, an estimated 9.3% of the world's population lived below this threshold, unable to afford adequate food, shelter, and other essentials. Sub-Saharan Africa had the highest share.", "q": "Define absolute poverty.", "ans": [["Unable to meet basic needs / below a fixed threshold", "living below minimum standard / survival level / poverty line"]], "concept": "Absolute = fixed line." },
  { "id": "2281_1c_52", "case": "In 2021, a large beverage company acquired a supplier that had provided it with packaging for 15 years. The firm now controls both the production of drinks and the manufacture of bottles and cans. The acquisition extended its control further back in the supply chain.", "q": "Define vertical integration.", "ans": [["Firm takes over another in the supply chain", "merge with supplier or distributor / backward integration"]], "concept": "Vertical = same industry, different stage." },

  /* --- From 2020 Specimen Paper 2 --- */
  { "id": "2281_1c_SP20_01", "case": "Kenya is a major exporter of cut flowers to Europe and Russia. On Women's Day (8 March), demand from Russian buyers typically doubles. Producers raise their prices sharply. Many consumers still buy flowers because they are considered essential for the occasion, and sales in volume terms fall by only around 15% despite the higher prices.", "q": "Explain the effect that a rise in the price of flowers on Women's Day in Russia would be likely to have on flower producers' revenue.", "ans": [["Increase / revenue rises", "demand is price-inelastic / PED less than one / inelastic demand / quantity falls by less than price rises"]], "concept": "0455 Specimen 2020 1(c). When PED < 1, price rise → revenue rises." },
  { "id": "2281_1c_SP20_02", "case": "In the financial year 2022–23, the government of Kenya spent 3.2 trillion shillings on health, education, infrastructure, and other services. Tax revenue and other income totalled 2.4 trillion shillings. The gap of 800 billion shillings was financed by borrowing from domestic and international lenders.", "q": "Define budget deficit.", "ans": [["Government spending exceeding government tax revenue", "spending greater than revenue / expenditure more than income"]], "concept": "0455 Specimen 2020 2(a)." },
  { "id": "2281_1c_SP20_03", "case": "In 2023, the government of Egypt fixed the price of subsidised bread at 5 piastres per loaf. Bakers are not allowed to charge more than this for the basic loaf. The policy was introduced so that low-income families could afford a staple food. Producers complained that the ceiling was below their costs.", "q": "Define maximum price.", "ans": [["A price that producers cannot charge above / price ceiling", "set by the government / upper limit on price"]], "concept": "0455 Specimen 2020 3(a)." },
  { "id": "2281_1c_SP20_04", "case": "A car factory in South Korea uses 500 tonnes of steel and 2,000 workers each month. The same steel could be used to build bridges or machinery. The workers could produce electronics or textiles. Choosing to make cars means that these resources cannot be used for other products.", "q": "Define economic good.", "ans": [["There is an opportunity cost involved in producing the good", "it takes resources to produce it / scarce resources"]], "concept": "0455 Specimen 2020 5(a)." },

  /* --- Past paper Q1(c) - Montenegro w23/23, Cyprus s22/21 --- */
  { "id": "2281_1c_PP_w23_23", "case": "Tourism is a very competitive market in Montenegro. Demand for holidays is price-elastic. Firms use this information when setting their prices. Most years, Montenegro attracts three times as many tourists as the number of people who live in the country.", "q": "Explain one way price elasticity of demand may influence firms' decision making.", "ans": [["Price elastic demand / elastic demand", "if they raise price revenue will fall / if they lower price revenue will rise / know price changes affect sales"], ["Price inelastic demand / inelastic demand", "if they raise price revenue will rise / if they lower price revenue will fall"]], "concept": "0455 w23 variant 23 (Montenegro) 1(c). 1 mark way, 1 mark explanation." },
  { "id": "2281_1c_PP_s22_21", "case": "In 2019, the global grape harvest was affected by bad weather. Global grape production fell by 35% which caused a shortage. Cyprus produces most of its own grapes and potatoes and exports a range of goods including fruit.", "q": "Explain one reason why a market may be in disequilibrium.", "ans": [["Supply fell / bad weather / harvest failure", "shortage occurred / demand exceeded supply"], ["Demand exceeded supply / shortage", "price below equilibrium / supply less than demand"]], "concept": "0455 s22 variant 21 (Cyprus) 1(c) adapted. Original: State why. MS: bad weather + shortage." },
  /* --- Past paper Q1(c) - 2024 --- */
  { "id": "2281_1c_PP_w24_21", "case": "The number of foreign nationals living in the UAE is higher than the number of citizens. Labour mobility between the UAE and other countries is high, with many daily flights landing from India and Pakistan. The UAE hosted the World Expo in 2021–2022.", "q": "Explain one factor that can influence labour mobility between countries.", "ans": [["Wage differences / higher pay", "workers move to countries with better pay / earn more"], ["Transport links / migration policies / visa", "easier to travel / fewer restrictions / more flights"], ["Availability of jobs / employment", "workers move where jobs exist / labour demand"]], "concept": "0455 w24 variant 21 (UAE) 1(c). 1 mark factor, 1 mark explanation." },
  { "id": "2281_1c_PP_s24_21", "case": "The number of Nicaraguans who were willing and able to work but could not find a job increased in 2020. This was calculated by both the claimant count and the labour force survey. Nicaragua has the lowest GDP per head in Central America.", "q": "Explain one way in which unemployment is measured.", "ans": [["Claimant count", "workers claiming unemployment benefits / those registered as jobseekers"], ["Labour force survey", "asking people if they are out of work and looking for employment / sample survey"]], "concept": "0455 s24 variant 21 (Nicaragua) 1(c). MS: claimant count or labour force survey." },
  /* --- Past paper Q1(c) - 2023 --- */
  { "id": "2281_1c_PP_s23_21", "case": "Some of the coal-mining firms in Queensland, Australia, are very large. They employ both low-paid, unskilled workers and high-paid specialist mining engineers, site managers and accountants. The firms use the latest excavators, mining drills, crushing equipment, earth movers and drones.", "q": "Explain one economy of scale that could benefit a coal-mining firm.", "ans": [["Managerial / labour economy", "employing specialist workers e.g. mining engineers / division of labour / efficiency"], ["Technical economy", "employing efficient equipment / e.g. excavators / drones / economies from large machinery"], ["External economy", "skilled labour force in area / suppliers nearby / infrastructure"]], "concept": "0455 s23 variant 21 (Australia coal) 1(c). 1 mark economy, 1 mark explanation." },
  /* --- Past paper Q1(c) - 2022 s22/22, s22/23, 2023 m23/22, 2024 s24/22 --- */
  { "id": "2281_1c_PP_s22_22", "case": "Bhutan's government spending in 2018 was $450m while tax revenue was $380m. The government announced increased spending on mental health, child poverty and pollution. Some economists argued that reducing income tax rates would be a better way to improve living standards.", "q": "Explain one way government spending may increase total demand in an economy.", "ans": [["Government spending exceeds tax revenue / budget deficit", "injection into economy / G component of AD increases"], ["Spending on infrastructure / health / education", "increases demand for goods and services / raises consumption or investment"]], "concept": "0455 s22 variant 22 (Bhutan) 1(c) adapted. Original: State why budget increased demand." },
  { "id": "2281_1c_PP_s22_23", "case": "A change in social attitudes has increased female participation in eSports. The Maltese government provides scholarships, work placements and brings in professionals to train students. Female participation in the labour force is encouraged. Malta's female labour force participation rate was 43% in 2019.", "q": "Explain one reason why more women may participate in the labour force.", "ans": [["Change in social attitudes", "less discrimination / more acceptance / cultural shift"], ["Better education / training", "improved skills / more job opportunities"], ["Government policy / incentives", "scholarships / support / equality measures"]], "concept": "0455 s22 variant 23 (Malta) 1(c) adapted. Original: Explain how social attitudes lead to participation." },
  { "id": "2281_1c_PP_s24_22", "case": "The Tunisian government regulates the price of flour and milk. Government control of these prices can help reduce poverty and prevent monopoly firms exploiting their market power. The government also subsidises electricity production.", "q": "Explain one reason why a government may regulate the price of a product.", "ans": [["Reduce poverty / help poor", "make essentials affordable / protect low-income consumers"], ["Prevent monopoly exploitation", "stop firms charging excessive prices / protect consumers"], ["Control inflation", "prevent price rises / stability"]], "concept": "0455 s24 variant 22 (Tunisia) 1(c). 1 mark reason, 1 mark explanation." },
  { "id": "2281_1c_PP_m23_22", "case": "The growth of US trade with China was affected by increases in US tariffs on some Chinese imports. These increases were expected to change the US current account balance, output and tax revenue. The US had a current account deficit of $470 billion in 2020.", "q": "Explain one way that import tariffs could improve an economy.", "ans": [["Protect domestic firms / industries", "reduce competition from imports / save jobs"], ["Improve current account", "reduce imports / reduce deficit on balance of payments"], ["Raise tax revenue", "government earns from tariff / revenue from duties"]], "concept": "0455 m23 variant 22 (US) 1(c). 1 mark way, 1 mark explanation." },
  /* --- Past paper Q1(c) - 2020 --- */
  { "id": "2281_1c_PP_s20_21", "case": "Vietnam's foreign exchange rate changed from $1 = 19,500 dong in 2010 to $1 = 22,780 dong in 2017. Vietnam's population and output increased over this period. Borrowing by both households and firms increased.", "q": "Explain one effect of currency depreciation on an economy.", "ans": [["Exports become cheaper / more competitive", "increase export demand / sales / more exports"], ["Imports become more expensive / costly imports", "higher costs for imported goods / import prices rise"]], "concept": "0455 s20 variant 21 (Vietnam) 1(c) adapted. Original: Explain what happened to exchange rate." },
  /* --- Past paper Q1(c) - 2021 --- */
  { "id": "2281_1c_PP_w21_21", "case": "Laos is a land-locked country, surrounded by Vietnam, Cambodia, Thailand, Myanmar and China. Access to seaports helps an economy take full advantage of international trade. A new rail link connecting China and Laos is expected to make transactions easier.", "q": "Explain one benefit of access to seaports for an economy.", "ans": [["Take full advantage of international trade", "export and import goods more easily / greater trading opportunities"], ["Lower transport costs", "goods transported more cheaply than by rail or air / over longer distances"], ["Encourage investment / attract MNCs", "firms prefer locations with port access / may create economic growth"]], "concept": "0455 w21 variant 21 (Laos) 1(c) adapted to Explain one. Original: Explain how." },
  /* --- From 2016 Indonesia (cocoa/specialisation pattern) --- */
  { "id": "2281_1c_S16_01", "case": "Indonesia specialises in producing cocoa. Farmers have gained expertise and the country has developed a reputation for quality beans.", "q": "Explain one advantage of an economy specialising.", "ans": [["Gain expertise / skills", "raise productivity / lower costs / higher output / more efficient"], ["Gain reputation", "increase demand / higher exports / better sales"]], "concept": "0455_s16 pattern. Same MS structure as Honduras." },

  /* --- From 2015 Lesotho / 2017 Botswana patterns (syllabus-aligned) --- */
  { "id": "2281_1c_S15_01", "case": "Kenya's cut flower industry generated $1 billion in exports in 2015. Real GDP per capita grew by 4.2% that year, and the central bank raised its benchmark interest rate from 8.5% to 10.5%. Bank deposits increased by 18% compared with 2014, according to the Kenya National Bureau of Statistics.", "q": "Explain one reason why the total amount saved in a country may increase.", "ans": [["Higher income / real GDP per head", "more disposable income to save"], ["Higher interest rate", "reward for saving / incentive to save / opportunity cost of spending"]], "concept": "0455 Specimen 2020 1(b) adapted to Explain one format." },
  { "id": "2281_1c_S17_01", "case": "In Botswana, public hospitals funded by the Ministry of Health provide treatment free of charge to citizens. In 2016, government spending on health accounted for 5.2% of GDP. Patients pay no fee at the point of use, and the service is financed mainly from diamond revenue and general taxation.", "q": "Explain one way a government provides healthcare.", "ans": [["Free healthcare / state provision", "funded by tax / reduces cost to users / improves access"], ["Subsidy to healthcare", "lowers price / makes it affordable"]], "concept": "0455 2017 Botswana extract pattern. Merit good / public provision." },

  /* --- From specimen Section B / common Define [2] patterns --- */
  { "id": "2281_1c_SB_01", "case": "Households in Egypt typically hold savings in the local currency. A survey in 2022 found that 65% of families kept cash at home for future expenses such as weddings or medical emergencies. Unlike perishable goods, money can be used to make purchases at a later date.", "q": "Define one function of money.", "ans": [["Store of value / store of wealth", "money can be kept for future use / retains value over time"]], "concept": "Money functions: medium, unit, store." },
  { "id": "2281_1c_SB_02", "case": "In 2021, Ghana's earnings from cocoa, gold, and oil exports totalled $14.2 billion. Its spending on imported machinery, fuel, and consumer goods was $16.8 billion. The country also had a deficit on its income and current transfers with the rest of the world.", "q": "Define a current account deficit.", "ans": [["Imports exceed exports / outflows exceed inflows", "deficit on trade / more money leaving than entering"], ["Spending on foreign trade and income exceeds earnings", "visible and invisible trade in deficit"]], "concept": "Current account = trade + flows." },
  { "id": "2281_1c_SB_03", "case": "A garment factory in Cambodia increased its workforce from 800 to 1,200 workers between 2019 and 2022. Total output rose from 2.4 million garments to 4.2 million. The management attributed much of the improvement to a new training scheme and investment in automated cutting machines.", "q": "Explain one reason why labour productivity may increase.", "ans": [["Better training / education", "workers more skilled / efficient"], ["Better technology / capital", "more output per worker / machines aid production"], ["Division of labour", "specialisation raises output"]], "concept": "Productivity = output per unit of input." },
  { "id": "2281_1c_SB_04", "case": "As the economy grew, the city suffered from thick smog and depletion of the local timber supply.", "q": "Explain one external cost of economic growth.", "ans": [["Air pollution / pollution", "health problems / environmental damage / negative externality"], ["Depletion of natural resources", "resource scarcity / less for future / deforestation"]], "concept": "0455 pattern. External cost = cost to third parties." },

  /* === Syllabus 0455/2281 2025-26 – source-based Explain one [2] === */
  { "id": "2281_1c_S25_01", "case": "Zambia has limited land and labour. A choice was made to use more land for maize production and less for cotton. The production possibility curve shows the maximum output of maize and cotton that can be produced with the resources available.", "q": "Explain one reason why an economy may not be able to produce more of all goods.", "ans": [["Limited resources / scarcity", "finite factors of production / land labour capital scarce"], ["Opportunity cost", "producing more of one good means producing less of another"]], "concept": "0455 Syllabus 1.1. Basic economic problem. Identify from source." },
  { "id": "2281_1c_S25_02", "case": "A cocoa farm in Ivory Coast employs 200 workers, uses tractors and irrigation equipment, and is run by an entrepreneur who bears the risk. The farm uses land that could otherwise grow rubber.", "q": "Explain one factor of production used in producing cocoa.", "ans": [["Land", "natural resources / space for farming"], ["Labour / labor", "workers / human effort"], ["Capital", "tractors / equipment / machinery"], ["Enterprise", "entrepreneur / risk bearing / organising production"]], "concept": "0455 Syllabus 1.2. Factors of production. Identify from source." },
  { "id": "2281_1c_S25_03", "case": "When the price of solar panels fell by 20% in 2023, the quantity demanded in Kenya increased by 35%. Households and firms switched from generators to solar power. The market cleared at the new lower price.", "q": "Explain one function of the price mechanism.", "ans": [["Rationing", "allocate scarce resources to those willing to pay / higher price rations demand"], ["Signalling", "price change signals scarcity or abundance / guides producers and consumers"], ["Incentive", "higher price encourages more supply / lower price encourages more demand"]], "concept": "0455 Syllabus 2.1. Allocation of resources. Price mechanism." },
  { "id": "2281_1c_S25_04", "case": "In Germany, a trade union negotiated a 5% pay rise for factory workers. The union represents over 2 million members and uses collective bargaining. Membership has grown as workers seek better wages and conditions.", "q": "Explain one benefit of trade union membership for workers.", "ans": [["Higher wages / pay", "collective bargaining gives more power than individual negotiation"], ["Better working conditions", "negotiate for safer conditions / shorter hours"], ["Job security", "protect workers from unfair dismissal"]], "concept": "0455 Syllabus 3.1. Workers and trade unions. Identify from source." },
  { "id": "2281_1c_S25_05", "case": "Two pharmaceutical companies merged in 2024 to form a larger firm. The merger was horizontal – both produced similar medicines. The new firm expected to cut costs by sharing research and marketing.", "q": "Explain one type of business growth.", "ans": [["Horizontal integration / merger", "merge with firm in same industry / same stage of production"], ["Vertical integration", "merge with supplier or distributor / different stage"], ["External growth", "growth through merger or takeover rather than organic"]], "concept": "0455 Syllabus 3.2. Firms – growth and mergers." },
  { "id": "2281_1c_S25_06", "case": "The EU restricts imports of rice from certain countries through an import quota. Only a fixed quantity of rice can be imported each year. The aim is to protect European rice producers from foreign competition.", "q": "Explain one method of protection.", "ans": [["Import quota", "limit on quantity of imports / restricts supply"], ["Tariff", "tax on imports / raises price of imports"], ["Embargo", "ban on imports or exports"]], "concept": "0455 Syllabus 6.2. Protection. Quota from source." },
  { "id": "2281_1c_S25_07", "case": "In the UK, a household is classified as being in relative poverty if its income is below 60% of the median household income. In 2023, about 14% of the population were in this position. They had less income than most other households.", "q": "Explain one measure of poverty.", "ans": [["Relative poverty", "income below a proportion of average / compared to others in society"], ["Absolute poverty", "below fixed line / cannot afford basic needs"]], "concept": "0455 Syllabus 5.2. Poverty. Relative vs absolute." },
  { "id": "2281_1c_S25_08", "case": "Costa Rica's Human Development Index improved between 2015 and 2023. Life expectancy rose, average years of schooling increased, and GNI per capita grew. The HDI combines these three indicators to measure development.", "q": "Explain one indicator of economic development.", "ans": [["Life expectancy", "average years people live / reflects healthcare"], ["Years of schooling / education", "human capital / skills"], ["GNI per capita / income", "average income per person"], ["HDI", "combines health education income"]], "concept": "0455 Syllabus 5.1. Living standards. HDI components." },
  { "id": "2281_1c_S25_09", "case": "Nigeria has a young population with 43% under 15. The working-age population (15–64) supports these dependents. The government has focused on education to improve the future labour force.", "q": "Explain one influence of population structure on an economy.", "ans": [["High dependency ratio", "many young or old per worker / pressure on working age"], ["Young population", "future labour force / need for schools and jobs"], ["Ageing population", "more elderly dependents / pension and healthcare costs"]], "concept": "0455 Syllabus 5.3. Population. Dependency ratio." },
  { "id": "2281_1c_S25_10", "case": "Rwanda has promoted sustainable development. Projects use renewable energy and aim to protect forests. The government argues that growth must not damage the environment for future generations.", "q": "Explain one way to achieve sustainable development.", "ans": [["Use renewable energy", "reduce pollution / protect resources"], ["Protect environment", "conserve forests / reduce emissions"], ["Balance growth and environment", "development without depleting resources"]], "concept": "0455 Syllabus 5.4. Development and sustainability." },
  { "id": "2281_1c_S25_11", "case": "In 2024, the government of Portugal reduced income tax rates and increased spending on roads and hospitals. Tax revenue was expected to fall in the short run. The deficit was financed by borrowing.", "q": "Explain one fiscal policy measure.", "ans": [["Reduce taxation", "increase disposable income / encourage spending"], ["Increase government spending", "injection into economy / raises total demand"], ["Budget deficit", "spending exceeds revenue / expansionary fiscal policy"]], "concept": "0455 Syllabus 4.3. Fiscal policy." },
  { "id": "2281_1c_S25_12", "case": "The government of Morocco set a maximum price for bottled cooking gas. Retailers cannot charge above this ceiling. The policy was introduced so that low-income families could afford this essential fuel. Some sellers reported shortages.", "q": "Explain one reason why a government may set a maximum price.", "ans": [["Reduce poverty / help poor", "make essentials affordable / protect low-income consumers"], ["Control inflation", "prevent price rises / stability"]], "concept": "0455 Syllabus 2.3. Government intervention. Max price." },
  { "id": "2281_1c_S25_13", "case": "Malaysia introduced a minimum wage of 1,500 ringgit per month for workers in urban areas. The government argued that this would raise living standards for low-paid workers. Some employers said it would increase their costs.", "q": "Explain one effect of a minimum wage.", "ans": [["Raise wages / income of low paid", "workers earn more / improve living standards"], ["Increase costs for firms", "employers pay more / may reduce employment"], ["Reduce poverty", "lowest paid get higher income"]], "concept": "0455 Syllabus 2.3. Minimum price. Min wage." },
  { "id": "2281_1c_S25_14", "case": "When Zambia's currency, the kwacha, was allowed to float freely, its value fluctuated against the US dollar. Exporters welcomed the flexibility but importers faced uncertainty over the cost of foreign goods.", "q": "Explain one advantage of a floating exchange rate.", "ans": [["Automatic adjustment", "balance of payments adjusts without intervention"], ["No need to hold reserves", "central bank does not defend rate"], ["Flexibility", "rate responds to market forces"]], "concept": "0455 Syllabus 6.3. Exchange rates. Float vs fixed." },
  { "id": "2281_1c_S25_15", "case": "Denmark's current account surplus grew in 2023. Earnings from exports of wind turbines and pharmaceuticals exceeded spending on imports. The country also received income from Danish firms' investments abroad.", "q": "Explain one component of the current account.", "ans": [["Balance of trade / visible trade", "exports minus imports of goods"], ["Income flows", "earnings from overseas investments / remittances"], ["Invisible trade", "trade in services"]], "concept": "0455 Syllabus 6.1. Balance of payments." }
];
