/**
 * Part D: Explain two [4 marks] - Q1(d) style
 * MS: 1 mark each for two identifications + 1 mark each for two explanations = 4 marks
 * Max 2 marks for list without explanation. Identification from source (see CR booklet).
 * ans = [ [Point1 pathways], [Point2 pathways] ] - two points, each with alternatives.
 * Sources: Exact from 0455/2281 past papers and specimen. Case = extract supporting answers.
 */
const partDData = [
  /* === EXACT from 0455_w23_22 (Honduras) - CR booklet exemplar === */
  { "id": "2281_1d_01", "case": "Honduras is a lower middle-income country. More than half of Honduran exports go to the US and 40% of imports come from the US. Hondurans work in the US and send money back. A successful clothes industry has the potential to reduce poverty. The Honduran government tries to reduce poverty by, for example, providing unemployment benefit. The country has a progressive income tax system, so there could be a significant rise in tax revenue. A more successful economy would raise incomes and encourage more investment.", "q": "Explain two ways a government could redistribute income.", "ans": [[["Provision of unemployment benefit / state benefit / welfare benefit", "raise income of those on low or no income / enable the unemployed to buy basic necessities / reduce absolute poverty"]], [["Progressive income tax system / progressive tax", "takes a higher proportion of the income of the rich / use some of tax revenue raised to increase spending to help those on low incomes"]]], "concept": "0455/22 O/N 2023 (Honduras) 1(d). MS verbatim. Identification from source." },
  /* === 0455 w23 variant 22 - 1(b) adapted: benefits from US growth (same Honduras extract) === */
  { "id": "2281_1d_02", "case": "Honduras relies heavily on trade with the US. More than half of Honduran exports go to the US and 40% of imports come from the US. A high number of Hondurans work in the US and send money back home to their relatives. A successful clothes industry has the potential to reduce poverty.", "q": "Explain two benefits the Honduran economy could gain from a growth in the US economy.", "ans": [[["Sell more exports to the US / more export demand", "US consumers buy more / higher sales for Honduran firms"]], [["Receive more money from Honduran workers in the US / more remittances", "households receive more income / spending increases / reduces poverty"]]], "concept": "0455 w23/22 1(b) extended. MS: sell more exports (1)+expl; receive more remittances (1)+expl." },
  /* === 0455 Specimen 2020 - Kenya (saving) === */
  { "id": "2281_1d_03", "case": "Kenya fact file 2015: population 47 million, labour force 18 million, unemployment rate 10%. In 2015 the Kenyan shilling depreciated and the interest rate rose to 16.5%. GDP increased. Kenya has a growing global reputation for high quality flowers.", "q": "Explain two reasons why the total amount saved in Kenya is likely to have increased in 2015.", "ans": [[["Higher income / real GDP per head", "more disposable income to save / people save more when they earn more"]], [["Higher interest rate", "reward for saving / incentive to save / makes saving more attractive"]]], "concept": "0455 Specimen 2020 1(d). 1+1 for each point. Max 2 for list only." },
  /* === Montenegro w23/23 - privatisation === */
  { "id": "2281_1d_04", "case": "Montenegro's banks now have more computers, more workers and more office buildings. All commercial banking, telecommunications and aluminium production has been transferred to the private sector. Tourism is a very competitive market.", "q": "Explain two benefits of transferring industries to the private sector.", "ans": [[["More efficiency / profit motive", "private firms aim to cut costs / increase productivity"]], [["More competition", "firms compete for customers / may lead to lower prices or better quality"]]], "concept": "0455 w23 variant 23 (Montenegro). Syllabus 4.4.2 privatisation." },
  /* === UAE w24/21 - labour mobility === */
  { "id": "2281_1d_05", "case": "The number of foreign nationals living in the UAE is higher than the number of citizens. Labour mobility between the UAE and other countries is high, with many daily flights from India and Pakistan. The UAE hosted the World Expo in 2021–2022.", "q": "Explain two benefits of high labour mobility for the UAE economy.", "ans": [[["Fill labour shortages", "workers come to do jobs / meet demand for labour"]], [["Bring skills / expertise", "skilled workers increase productivity / transfer knowledge"]]], "concept": "0455 w24 variant 21 (UAE) 1(d)." },
  /* === Laos w21/21 - financial sector === */
  { "id": "2281_1d_06", "case": "The financial sector, including commercial banks, is growing in Laos. This has enabled local entrepreneurs to borrow money and encouraged more households to save. Laos exports 58% of its goods to China.", "q": "Explain two benefits of a growing financial sector for an economy.", "ans": [[["Helps entrepreneurs borrow / lending", "firms can invest / expand / create jobs"]], [["Encourages saving", "households save more / funds available for investment"]]], "concept": "0455 w21 variant 21 (Laos) 1(d)." },
  /* === Mauritius w22/21 - economic growth and living standards === */
  { "id": "2281_1d_07", "case": "The economy of Mauritius has grown since it changed from primary to tertiary sector. The growth increased income per head and improved healthcare. Life expectancy has increased and the infant mortality rate has fallen significantly.", "q": "Explain two benefits of economic growth for living standards in Mauritius.", "ans": [[["Higher income per head", "people can afford more goods and services / better quality of life"]], [["Improved healthcare", "life expectancy rises / infant mortality falls / people live longer healthier lives"]]], "concept": "0455 w22 variant 21 (Mauritius) 1(d)." },
  /* === Vietnam s20/21 - currency depreciation === */
  { "id": "2281_1d_08", "case": "Vietnam's GDP grew from $272.8bn to $662.4bn between 2010 and 2017. The exchange rate changed from $1=19,500 dong to $1=22,780 dong. Borrowing by households and firms increased. Wages and pensions have risen.", "q": "Explain two effects of currency depreciation on the Vietnamese economy.", "ans": [[["Exports become cheaper / more competitive", "foreign buyers pay less / demand for exports rises"]], [["Imports become more expensive", "higher costs for imported goods / cost-push inflation"]]], "concept": "0455 s20 variant 21 (Vietnam) 1(d)." },
  /* === Australia s23/21 - coal demand === */
  { "id": "2281_1d_09", "case": "Global demand for coal has declined as countries switched to gas, offshore wind and solar power. Australia is a major producer of coal. Some coal-mining firms are very large and use excavators, drilling equipment and drones.", "q": "Explain two reasons why demand for coal has fallen.", "ans": [[["Switch to substitutes / gas / renewables", "countries use cheaper or cleaner alternatives / gas wind solar"]], [["Environmental concerns / climate change", "coal causes pollution / countries want to reduce emissions"]]], "concept": "0455 s23 variant 21 (Australia) 1(d)." },
  /* === Cyprus s22/21 - living standards indicators === */
  { "id": "2281_1d_10", "case": "Cyprus had a relatively high HDI ranking in 2019. Life expectancy rose from 79 to 81 years. GDP per head increased from $23,334 to $27,900. Cyprus exports fruit, pharmaceuticals and clothing.", "q": "Explain two indicators that suggest living standards improved in Cyprus between 2015 and 2019.", "ans": [[["Life expectancy increased", "people living longer / reflects better healthcare"]], [["GDP per head increased", "higher average income / more goods and services per person"]]], "concept": "0455 s22 variant 21 (Cyprus) 1(d). HDI components." },
  /* === Malta s22/23 - eSports demand === */
  { "id": "2281_1d_11", "case": "eSports demand has increased because of increases in incomes and decreases in the price of the technology needed to play or watch. A change in social attitudes has increased female participation. Malta provides scholarships and work placements.", "q": "Explain two reasons why demand for eSports has increased.", "ans": [[["Higher incomes", "people can afford to spend more on entertainment / normal good"]], [["Cheaper technology", "lower cost to play or watch / price of equipment fell"]]], "concept": "0455 s22 variant 23 (Malta) 1(d). Conditions of demand." },
  /* === Bhutan s22/22 - budget deficit === */
  { "id": "2281_1d_12", "case": "Bhutan's government spending in 2018 was $450m while tax revenue was $380m. The government announced increased spending on mental health, child poverty and pollution. Bhutan's labour force is mostly in agriculture.", "q": "Explain two reasons why a government may run a budget deficit.", "ans": [[["Increase spending on priorities", "health education infrastructure / meet public needs"]], [["Recession / low tax revenue", "tax intake falls when economy slows / automatic stabiliser"]]], "concept": "0455 s22 variant 22 (Bhutan) 1(d)." },
  /* === US m23/22 - tariffs === */
  { "id": "2281_1d_13", "case": "The growth of US trade with China was affected by increases in US tariffs on some Chinese imports. These were expected to change the US current account balance, output and tax revenue. The US had a current account deficit of $470 billion in 2020.", "q": "Explain two ways that import tariffs could improve an economy.", "ans": [[["Protect domestic firms / industries", "reduce competition from imports / save jobs"]], [["Improve current account / reduce deficit", "fewer imports / reduce deficit on balance of payments"], ["Raise tax revenue", "government earns from tariff / revenue from duties"]]], "concept": "0455 m23 variant 22 (US) 1(d). Point 2: two from – improve CA, raise revenue." },
  /* === Nicaragua s24/21 - unemployment causes === */
  { "id": "2281_1d_14", "case": "Nicaragua has a large agricultural sector. Wages are particularly low in rural areas. The number of Nicaraguans willing and able to work but unable to find a job increased in 2020. Nicaragua has the lowest GDP per head in Central America.", "q": "Explain two possible causes of unemployment in Nicaragua.", "ans": [[["Lack of jobs / demand-deficient", "not enough employment opportunities / recession"]], [["Skill mismatch / structural", "workers lack skills employers need / mismatch between jobs and workers"]]], "concept": "0455 s24 variant 21 (Nicaragua). Syllabus 4.7 unemployment." },
  /* === Tunisia s24/22 - government intervention === */
  { "id": "2281_1d_15", "case": "The Tunisian government regulates the price of flour and milk. Government control can help reduce poverty and prevent monopoly firms exploiting their market power. The government also subsidises electricity production.", "q": "Explain two reasons why a government may intervene in a market.", "ans": [[["Reduce poverty", "make essentials affordable / protect low-income consumers"]], [["Prevent monopoly exploitation", "stop firms charging excessive prices / protect consumers"]]], "concept": "0455 s24 variant 22 (Tunisia) 1(d)." },
  /* === Cambridge w23/21 - knowledge-intensive exports === */
  { "id": "2281_1d_16", "case": "Many firms in Cambridge operate in education, healthcare, research and development, and hi-tech manufacturing. Cambridge firms' exports are highly knowledge-intensive, making them highly priced. Increasing global incomes have increased demand for services such as education from Cambridge.", "q": "Explain two benefits of having highly knowledge-intensive exports.", "ans": [[["Higher prices / premium pricing", "firms can charge more / inelastic demand"]], [["Demand rises with global incomes", "as world gets richer demand for education healthcare rises"]]], "concept": "0455 w23 variant 21 (Cambridge) 1(d)." },
  /* --- From Past Papers folder: s21, m23, s23, s24, w24, w22, w21 --- */
  { "id": "2281_1d_17", "case": "The Nigerian government uses policy measures including subsidising the training of construction workers. Successful training can increase job opportunities and wages. The government aims to improve Nigeria's macroeconomic performance and raise living standards.", "q": "Explain how government spending on training may increase tax revenue in the long run.", "ans": [[["Training may increase skills of workers", "raise productivity / raise wages / increase job opportunities / employment / increase income tax revenue"]], [["Higher wages may increase spending", "increase indirect tax revenue / more consumption"], ["More productive labour force may reduce costs", "raise profits / increase corporation tax revenue"]]], "concept": "0455 s21 variant 21 (Nigeria) 1(d). 4 marks. Two logical chains." },
  { "id": "2281_1d_18", "case": "In 2020, US macroeconomic performance changed. The country's price level rose more slowly, largely due to a decrease in consumer expenditure and a reduction in workers' bargaining power. Real GDP fell and unemployment rose.", "q": "Explain two reasons why the US inflation rate fell in 2020.", "ans": [[["Fall in consumer expenditure", "lower total demand / reduce demand-pull inflation"]], [["Reduction in workers' bargaining power", "fall in wage rises / fall in costs / reduce cost-push inflation"], ["Higher unemployment", "reduces confidence / lower total demand / fall in consumer spending"], ["Fall in real GDP", "lower incomes / purchasing power / lower total demand"]]], "concept": "0455 m23 variant 22 (US) 1(d)." },
  { "id": "2281_1d_19", "case": "Coal can be stored to meet changes in market conditions but storage costs can be high. It can also take years to construct a new coal mine. Global coal production has fallen with most countries switching to renewables.", "q": "Explain two influences on the price elasticity of supply of coal.", "ans": [[["Storage time / expensive to store", "inelastic supply / hard to store"]], [["Construction of new mine / production time", "takes long time / inelastic supply"], ["Stocks / stockpiles", "may make supply more elastic"]]], "concept": "0455 s23 variant 21 (Australia) 1(d)." },
  { "id": "2281_1d_20", "case": "The purchasing power of Nicaraguan consumers fell in 2020 as prices rose by more than incomes. The cordoba continued to act as a medium of exchange and store of value. Nicaragua has the lowest GDP per head in Central America.", "q": "Explain two functions of money in Nicaragua.", "ans": [[["Medium of exchange", "used to buy and sell products / used to trade"]], [["Store of value", "used to save / keeps its value over a period of time"]]], "concept": "0455 s24 variant 21 (Nicaragua) 1(d)." },
  { "id": "2281_1d_21", "case": "One of Jordan's main industries is tourism. Recent years have seen mergers between some of Jordan's tourism firms. These mergers reduced the prices of some holidays and raised their quality.", "q": "Explain two advantages the Jordanian economy may gain from the mergers between its tourism firms.", "ans": [[["Lower prices", "may raise output / GDP / employment / living standards / economies of scale"]], [["Higher quality", "may raise exports / reduce current account deficit / increase competitiveness / more tourism revenue"]]], "concept": "0455 w24 variant 22 (Jordan) 1(d)." },
  { "id": "2281_1d_22", "case": "Mauritius is known for many attractions including its beautiful beaches. More than a million tourists visit each year. Tourists from most countries only need their passport as a visa is not required. The government spent more than $1 billion on infrastructure in 2019, upgrading the airport, seaport and public transport.", "q": "Explain two reasons why millions of tourists visit Mauritius each year.", "ans": [[["Tourist attractions / beautiful beaches", "attractive destination / natural beauty"]], [["Easy to travel / no visa required", "just need passport / fewer restrictions"], ["Good infrastructure", "good airports / ports / public transport"]]], "concept": "0455 w22 variant 21 (Mauritius) 1(d)." },
  { "id": "2281_1d_23", "case": "Laos has introduced free market reforms. The financial sector is growing. Laos exports 58% of its goods to China. A new rail link connecting China and Laos is expected to make transactions easier.", "q": "Explain two benefits of the free market reforms introduced by the government of Laos.", "ans": [[["Sell raw materials internationally", "increases export revenue / improves current account / creates employment / increases GDP"]], [["Encourages foreign investment", "may lower costs / increases total demand / creates jobs / increases tax revenue"]]], "concept": "0455 w21 variant 21 (Laos) 1(d)." },
  { "id": "2281_1d_24", "case": "The Tunisian government increased labour market information for workers and employers. It did not raise unemployment benefit in line with inflation. Tunisia had high unemployment. The government regulates flour and milk prices.", "q": "Explain two ways the Tunisian government tried to reduce frictional unemployment.", "ans": [[["Increased labour market information / information available to workers and employers", "workers aware of job vacancies / skills and qualifications required / reduce search time / increase mobility / move more quickly between jobs"]], [["Did not raise unemployment benefit in line with inflation", "purchasing power of benefit would fall / increase incentive to work"]]], "concept": "0455 s24 variant 22 (Tunisia) 1(d). MS verbatim 2281_s24_ms_22." },
  /* === Cambridge w23/21 - Explain how: education reduces poverty (from economics_extraction.json) === */
  { "id": "2281_1d_25", "case": "Cambridge ranks number one amongst UK cities for workers with university qualifications. Around 70% of workers have a degree. Many firms operate in education, healthcare, R&D and hi-tech manufacturing. Poverty reduction is often linked to raising the skills of the labour force.", "q": "Explain how having a more educated labour force can reduce poverty.", "ans": [[["More educated / skilled / productive", "earn higher wages / afford basic necessities / higher income"]], [["More job opportunities / less unemployment", "wages exceed unemployment benefits / incentive to work"], ["Access to health information", "ability to work / better healthcare"]]], "concept": "0455/21 w23 (Cambridge) 1(d). 4 marks. MS: skills->wages->necessities; jobs->wages>benefit; health info." },
  /* --- Additional from Past Papers (s22, s25, m25, m21, m22, m24, s23, s24, w21-w25 variants) --- */
  { "id": "2281_1d_26", "case": "In Cyprus, more workers are now working past retirement age. This is particularly true of highly qualified workers who tend to be well-paid, healthy and have jobs that do not require physical strength. Cyprus had a high HDI ranking in 2019.", "q": "Explain two reasons why more well-educated workers tend to work past retirement age than less-educated workers.", "ans": [[["Better health", "jobs less physically demanding / can work longer"]], [["Higher pay / job satisfaction", "incentive to continue / enjoy work / financially rewarding"]]], "concept": "0455 s22 variant 21 (Cyprus) 1(d)." },
  { "id": "2281_1d_27", "case": "Bhutan's labour force is mostly in agriculture. Working conditions, working hours, the type of work and pay vary between the primary and tertiary sectors. Bhutan exports hydropower and tourism has grown.", "q": "Explain two reasons why someone may prefer to work in the tertiary sector rather than in the primary sector.", "ans": [[["Better pay / higher wages", "tertiary often pays more / higher income"]], [["Better working conditions", "less physical / indoors / more comfortable / regular hours"]]], "concept": "0455 s22 variant 22 (Bhutan) 1(d)." },
  { "id": "2281_1d_28", "case": "Romania's economy has grown in recent years. Wages have increased and consumer credit has become more widely available. Household spending has risen as a share of GDP.", "q": "Explain two reasons why household spending has increased in Romania.", "ans": [[["Higher incomes / wages", "more disposable income / can afford more goods and services"]], [["Easier credit / borrowing", "consumers can buy now pay later / access to loans"]]], "concept": "0455 m25 variant 22 (Romania) 1(d)." },
  { "id": "2281_1d_29", "case": "St. Kitts and Nevis has a growing financial sector and a citizenship by investment programme. Tourism is a major industry. The country has attracted international banks and offers tax advantages for certain activities.", "q": "Explain two reasons why a foreign bank may open a branch in St. Kitts and Nevis.", "ans": [[["Profit motive / grow business", "serve tourists / wealthy residents / expand market"]], [["Stable regulation / tax advantages", "favourable conditions / citizenship investors need banking"]]], "concept": "0455 s25 variant 22 (St. Kitts and Nevis) 1(d)." },
  { "id": "2281_1d_30", "case": "Egypt has seen growth in its manufacturing and services sectors. The government has invested in education and infrastructure. Remittances from Egyptians working abroad have increased.", "q": "Explain two reasons why economic growth may reduce unemployment in Egypt.", "ans": [[["More jobs created", "firms expand / hire more workers"]], [["Higher demand for labour", "output rises / need more workers"]]], "concept": "0455 s25 variant 23 (Egypt) 1(d). Growth and employment." },
  { "id": "2281_1d_31", "case": "Pakistan's population is young and the labour force is growing. The government has raised spending on vocational training. Many workers move abroad for employment.", "q": "Explain two benefits of vocational training for an economy.", "ans": [[["Reduce skill mismatch / structural unemployment", "workers have skills employers need"]], [["Raise productivity", "skilled workers produce more / higher output"]]], "concept": "0455 m21/m22 pattern. Supply-side policy." },
  { "id": "2281_1d_32", "case": "Bangladesh's garment industry employs millions of workers. Garment exports have grown but competition from other countries has increased. The government has considered subsidies to support the industry.", "q": "Explain two reasons why a government may subsidise an industry.", "ans": [[["Protect jobs / employment", "prevent job losses / support workers"], ["Improve competitiveness", "lower costs / help firms compete"]], [["Infant industry / develop sector", "new firms need support / encourage growth"]]], "concept": "0455 m22/m24 pattern. Subsidy rationale." },
  { "id": "2281_1d_33", "case": "Indonesia is rich in natural resources including palm oil, rubber and coal. The country has sought to add value to its exports by developing processing industries. Manufacturing has grown in recent years.", "q": "Explain two benefits of adding value to exports for an economy.", "ans": [[["Higher export revenue", "processed goods earn more than raw materials"]], [["Create jobs / employment", "processing creates more jobs than exporting raw materials"]]], "concept": "0455 s23 variant 22 (Indonesia) 1(d)." },
  { "id": "2281_1d_34", "case": "Malta has encouraged female participation in the labour force through scholarships and work placements. The government also provides childcare support. Female labour force participation has risen.", "q": "Explain two benefits of higher female labour force participation for an economy.", "ans": [[["Increase total output / GDP", "more workers / larger labour force"]], [["Raise tax revenue", "more people earning and paying tax"], ["Reduce skill shortages", "use full talent of population"]]], "concept": "0455 s23 variant 23 (Malta) 1(d)." },
  { "id": "2281_1d_35", "case": "Kenya exports cut flowers to Europe. The industry employs many workers in rural areas. Flower farms have invested in irrigation and cold storage. Demand for flowers has grown with rising incomes in importing countries.", "q": "Explain two reasons why the value of Kenya's flower exports may have increased.", "ans": [[["Rising incomes in importing countries", "demand for flowers rises / normal good"], ["Higher prices", "demand exceeds supply / scarcity"]], [["More production / supply", "investment in irrigation / cold storage / higher output"]]], "concept": "0455 s24 variant 23 (Kenya) 1(d)." },
  { "id": "2281_1d_36", "case": "Thailand has signed free trade agreements with several countries. Tariffs on many goods have been reduced or removed. Thai exports of electronics and vehicles have grown.", "q": "Explain two benefits of free trade for Thailand.", "ans": [[["Access to larger markets", "sell more exports / increase sales"]], [["Cheaper imports", "lower costs for consumers and firms / raw materials"], ["Specialisation", "produce what Thailand does best / efficiency"]]], "concept": "0455 w21 variant 22 (Thailand) 1(d)." },
  { "id": "2281_1d_37", "case": "Malawi relies heavily on agriculture. Many farmers grow maize for local consumption. When harvests are good, maize prices fall. The government has considered buffer stocks to stabilise prices.", "q": "Explain two reasons why agricultural prices may fluctuate.", "ans": [[["Weather / harvests vary", "supply changes / good or bad harvest"], ["Seasonality", "supply varies through the year"]], [["Inelastic demand", "small change in supply causes big price change"]]], "concept": "0455 w21 variant 23 (Malawi) 1(d)." },
  { "id": "2281_1d_38", "case": "Botswana's economy depends on diamonds. The government has used diamond revenue to fund education and healthcare. Botswana has one of the highest rates of HIV treatment in Africa.", "q": "Explain two ways the Botswana government could use tax revenue to improve living standards.", "ans": [[["Spend on education", "improve skills / raise future incomes"]], [["Spend on healthcare", "better health / life expectancy / productivity"], ["Reduce poverty / provide benefits", "support low-income families"]]], "concept": "0455 w22 variant 22 (Botswana) 1(d)." },
  { "id": "2281_1d_39", "case": "Singapore has few natural resources but has developed a highly skilled workforce. The country attracts foreign investment and has become a hub for finance and technology. GDP per head is among the highest in the world.", "q": "Explain two reasons why Singapore has attracted foreign investment.", "ans": [[["Skilled workforce", "productive labour / quality workers"], ["Stable government / rule of law", "predictable environment / property rights"]], [["Good infrastructure", "transport / communications / efficiency"]]], "concept": "0455 w22 variant 23 (Singapore) 1(d)." },
  { "id": "2281_1d_40", "case": "India has a large young population. Many workers are employed in the informal sector. The government has introduced schemes to encourage firms to register and pay tax. Digital payment systems have grown rapidly.", "q": "Explain two benefits of a larger formal sector for an economy.", "ans": [[["Higher tax revenue", "government can collect more tax"], ["Better working conditions", "workers have rights / protections"]], [["More reliable data", "government can plan policy better"]]], "concept": "0455 w23 variant 22 (India) 1(d)." },
  { "id": "2281_1d_41", "case": "Saudi Arabia is reducing its reliance on oil. The government has invested in tourism, renewable energy and technology. Vision 2030 aims to diversify the economy.", "q": "Explain two benefits of economic diversification for Saudi Arabia.", "ans": [[["Reduce reliance on one industry", "less vulnerable to oil price changes"], ["Create new jobs", "tourism / renewables / technology sectors grow"]], [["More stable revenue", "not dependent on single export"]]], "concept": "0455 w24 variant 21 (UAE/Saudi pattern) 1(d)." },
  { "id": "2281_1d_42", "case": "Rwanda has invested heavily in technology and innovation. The government has promoted mobile banking and digital services. Kigali aims to become a technology hub for East Africa.", "q": "Explain two benefits of technology for economic development.", "ans": [[["Raise productivity", "efficiency / automation / more output"], ["Improve access to finance", "mobile banking / financial inclusion"]], [["Create new industries", "tech sector jobs / innovation"]]], "concept": "0455 w24 variant 23 (Rwanda) 1(d)." },
  { "id": "2281_1d_43", "case": "Brazil is a major exporter of soybeans, beef and iron ore. The country has faced deforestation concerns. The government has tried to balance economic growth with environmental protection.", "q": "Explain two reasons why a government may want to protect the environment.", "ans": [[["Sustainable development", "preserve for future generations"], ["External costs", "pollution harms society / health costs"]], [["Tourism", "natural beauty attracts visitors / revenue"]]], "concept": "0455 w25 variant 21 (Brazil) 1(d)." },
  { "id": "2281_1d_44", "case": "Vietnam has become a major manufacturer of electronics and textiles. Many multinational companies have set up factories there. Wages have risen as the economy has grown.", "q": "Explain two benefits of multinational companies for Vietnam.", "ans": [[["Create jobs / employment", "hire local workers"], ["Transfer technology / skills", "workers learn new skills"]], [["Increase exports", "output sold abroad / improve current account"]]], "concept": "0455 w25 variant 22 (Vietnam) 1(d)." },
  { "id": "2281_1d_45", "case": "Ghana exports cocoa, gold and oil. The country has experienced currency fluctuations. A depreciating currency has helped some exporters but raised the cost of imported fuel and machinery.", "q": "Explain two effects of currency depreciation on an economy.", "ans": [[["Exports become cheaper / more competitive", "foreign buyers pay less / demand for exports rises"]], [["Imports become more expensive", "higher costs for imported goods / cost-push inflation"]]], "concept": "0455 w25 variant 23 (Ghana) 1(d). Same pattern as Vietnam 1d_08." },

  /* === Syllabus 0455/2281 2025-26 – source-based Explain two [4] === */
  { "id": "2281_1d_S25_01", "case": "A trade union in South Africa has over 200,000 members in the mining sector. The union negotiates wages and working conditions through collective bargaining. It also provides legal support to members who face dismissal. Membership has grown as workers seek better pay and job security.", "q": "Explain two benefits of trade union membership for workers.", "ans": [[["Collective bargaining / higher wages", "more power than individual / negotiate better pay"]], [["Job security / legal support", "protection from unfair dismissal / representation"]]], "concept": "0455 Syllabus 3.1. Trade unions. Identification from source." },
  { "id": "2281_1d_S25_02", "case": "The national water company in Uruguay is the only supplier of piped water to households. There are no competitors. The regulator has limited the price it can charge but many consumers complain about poor service and lack of choice.", "q": "Explain two disadvantages of a monopoly for consumers.", "ans": [[["Higher prices", "no competition / can charge more"], ["Lack of choice", "no alternative supplier / one product only"]], [["Poor quality / service", "no incentive to improve / consumers have no alternative"]]], "concept": "0455 Syllabus 3.2. Monopoly disadvantages." },
  { "id": "2281_1d_S25_03", "case": "Consumer spending in Turkey increased by 25% in 2023. At the same time, the cost of imported energy and raw materials rose sharply. Wage increases were negotiated by trade unions. The inflation rate reached 65%.", "q": "Explain two causes of inflation in Turkey.", "ans": [[["Demand-pull", "consumer spending rose / total demand exceeded supply"], ["Cost-push", "energy and raw material costs rose / wage increases"]], [["Import costs", "depreciation or higher world prices raise cost of imports"]]], "concept": "0455 Syllabus 4.2. Inflation causes." },
  { "id": "2281_1d_S25_04", "case": "The government of Poland has invested in vocational training and reduced business regulations. It has also cut corporation tax to encourage firms to invest. The aim is to increase the economy's productive potential and reduce unemployment.", "q": "Explain two supply-side policy measures.", "ans": [[["Education / training", "improve skills / productivity / human capital"], ["Deregulation", "reduce rules / lower costs / encourage enterprise"]], [["Reduce corporation tax", "encourage investment / firms retain more profit"]]], "concept": "0455 Syllabus 4.4. Supply-side policy." },
  { "id": "2281_1d_S25_05", "case": "A Japanese car manufacturer opened a factory in Mexico in 2023, employing 3,000 local workers. The firm provided training in robotics and quality control. It also sourced parts from local suppliers. The factory exports cars to the US.", "q": "Explain two benefits of foreign direct investment for Mexico.", "ans": [[["Jobs / employment", "creates jobs / hires local workers"], ["Training / skills transfer", "workers learn new skills / technology transfer"]], [["Exports", "output sold abroad / improves current account"]]], "concept": "0455 Syllabus 6.4. FDI benefits." },
  { "id": "2281_1d_S25_06", "case": "Brazil has protected its ethanol industry with tariffs on imported fuel. The government argues that domestic producers need time to develop and that cheap imports would destroy local jobs. Critics say it raises prices for consumers.", "q": "Explain two reasons why a government may protect an industry.", "ans": [[["Infant industry", "new firms need time to grow / develop"], ["Protect jobs", "prevent job losses / save employment"]], [["Prevent dumping", "stop unfair competition from cheap imports"]]], "concept": "0455 Syllabus 6.2. Protection reasons." },
  { "id": "2281_1d_S25_07", "case": "Table: Country A – life expectancy 72, GNI per capita $4,200, mean years schooling 8. Country B – life expectancy 58, GNI per capita $1,100, mean years schooling 4. Both are used to calculate the Human Development Index.", "q": "Explain two indicators that could be used to compare living standards between countries.", "ans": [[["Life expectancy", "reflects healthcare / how long people live"], ["GNI per capita", "average income / purchasing power"]], [["Years of schooling / education", "human capital / skills"]]], "concept": "0455 Syllabus 5.1. HDI / living standards." },
  { "id": "2281_1d_S25_08", "case": "Ethiopia's population has grown rapidly. The birth rate remains high and the death rate has fallen due to better healthcare. The working-age population has to support a large number of young dependents. Schools and hospitals are under pressure.", "q": "Explain two effects of a rapidly growing population on an economy.", "ans": [[["Pressure on resources", "schools hospitals housing stretched / more demand for services"], ["High dependency ratio", "many young per worker / less saving and investment"]], [["Strain on jobs", "more people seeking work / unemployment may rise"]]], "concept": "0455 Syllabus 5.3. Population growth." },
  { "id": "2281_1d_S25_09", "case": "A cement plant in Pakistan emits dust that affects nearby villages. The government has imposed a tax on emissions and set limits on pollution. Firms must install filters or pay the tax. The policy aims to reduce the external cost imposed on residents.", "q": "Explain two ways a government could reduce pollution.", "ans": [[["Tax on pollution / emissions", "internalise external cost / firms pay for damage"], ["Regulation / limits", "set maximum emissions / fines for exceeding"]], [["Subsidy for clean technology", "encourage firms to invest in filters"]]], "concept": "0455 Syllabus 2.3. Market failure – externalities." },
  { "id": "2281_1d_S25_10", "case": "Colombia specialises in producing coffee and flowers. Farmers have gained expertise in these crops and the country has developed a reputation for quality. Colombia exports these products to many countries. Some economists argue this specialisation has made the economy vulnerable to price changes.", "q": "Explain two benefits of an economy specialising.", "ans": [[["Gain skills / expertise", "raise productivity / lower costs / more efficient"], ["Gain reputation", "increase demand / higher exports / premium prices"]], [["Economies of scale", "produce more of fewer products / lower average cost"]]], "concept": "0455 Syllabus 1.4 / 6.1. Specialisation." },
  { "id": "2281_1d_S25_11", "case": "The central bank of India raised interest rates in 2023 to reduce inflation. It also sold government bonds to reduce the money supply. Inflation had risen due to high consumer spending and rising food prices. The aim was to slow total demand.", "q": "Explain two monetary policy tools that could reduce inflation.", "ans": [[["Raise interest rates", "cost of borrowing rises / less spending and investment"], ["Sell bonds / open market operations", "reduce money supply / tight monetary policy"]], [["Increase reserve requirements", "banks lend less / money supply falls"]]], "concept": "0455 Syllabus 4.3. Monetary policy." },
  { "id": "2281_1d_S25_12", "case": "Senegal has a large informal sector. Many workers sell goods in street markets and do not pay tax. The government has introduced a scheme to register businesses and offer tax benefits. It hopes to bring more activity into the formal sector and increase tax revenue.", "q": "Explain two benefits of a larger formal sector for an economy.", "ans": [[["Higher tax revenue", "government can collect more tax / finance public services"], ["Better working conditions", "workers have legal rights / minimum wage"]], [["More reliable data", "government can plan policy better"]]], "concept": "0455 Syllabus 3.1 / 5.4. Formal vs informal." },
  { "id": "2281_1d_S25_13", "case": "When oil prices rose sharply in 2022, the cost of producing fertiliser increased. Farmers faced higher input costs. At the same time, consumer demand for food remained strong. Food prices rose in many countries.", "q": "Explain two causes of inflation.", "ans": [[["Cost-push", "oil and fertiliser costs rose / input prices increased"], ["Demand-pull", "strong consumer demand / demand exceeded supply"]], [["Rise in costs of production", "raw materials / energy more expensive"]]], "concept": "0455 Syllabus 4.2. Inflation." },
  { "id": "2281_1d_S25_14", "case": "Kenya has encouraged microfinance institutions to lend to small businesses. Banks have also expanded mobile banking. Household savings have risen as more people can access secure accounts. Entrepreneurs report that borrowing has become easier.", "q": "Explain two benefits of a developed financial sector for an economy.", "ans": [[["Encourages saving", "secure place to save / funds for investment"], ["Enables borrowing / lending", "firms and households can borrow / invest and spend"]], [["Facilitates trade", "payments easier / medium of exchange"]]], "concept": "0455 Syllabus 5.4. Financial sector and development." },
  { "id": "2281_1d_S25_15", "case": "Chile signed a free trade agreement with the EU. Tariffs on many goods were removed. Chilean wine and fruit exporters gained access to a larger market. At the same time, some Chilean manufacturers faced more competition from European imports.", "q": "Explain two benefits of free trade for Chile.", "ans": [[["Access to larger markets", "sell more exports / increase sales"], ["Cheaper imports", "consumers and firms pay less / wider choice"]], [["Specialisation", "produce what Chile does best / efficiency gains"]]], "concept": "0455 Syllabus 6.1. Free trade." }
];
