// Section B Part (a) - Paper 2 Q2(a), Q3(a), Q4(a), Q5(a) style
// Question styles: Define with example [2] | Define [2] | Identify two [2]
// Sources: Past papers 2021-2025 (W/S/M series), syllabus coverage (0455/2281)
const sectionBPartAData = [
  // ═══════════════════════════════════════════════════════════════
  // PAST PAPERS 2021–2025 (from QP + MS)
  // ═══════════════════════════════════════════════════════════════
  // --- W21 ---
  { "id": "SBa_W21_2a", "case": "A number of countries, including Morocco, capture water from fog. Water is used in the primary, secondary and tertiary sectors. In recent years, Morocco has increased the quantity and quality of its resources and has moved more of them into the tertiary sector. The quantity, quality and composition of a country's resources are influenced by a number of factors, including its birth rate. Morocco's birth rate fell from 19.9 in 2016 to 18.7 in 2018.", "q": "Define a free good.", "ans": ["No opportunity cost", "Good that takes no resources to produce / naturally abundant in supply"], "concept": "MS: No opportunity cost (1) + no resources/abundant (1)." },
  { "id": "SBa_W21_3a", "case": "Two of Uzbekistan's main industries are cotton and gas. Uzbekistan is the world's seventh largest producer, and fifth largest exporter, of cotton. The Uzbek government has tried to influence the cotton industry's price elasticity of supply. It has also nearly ended the use of child labour in cotton production. The country's output of gas increased by 7% in 2018 and its average cost of gas production fell.", "q": "Identify two determinants of price elasticity of supply.", "ans": ["Ability to store / level of stocks", "Production time / spare capacity"], "concept": "MS: ability to store, level of stocks, perishability, production time, spare capacity, cost of altering supply." },
  { "id": "SBa_W21_4a", "case": "In Tunisia, resource allocation decisions are made by both the public sector and private sector. Tunisia's GDP increased from 2014 to 2018 but its households saved less. Income levels can be affected by changes in trade union activity and the foreign exchange rate. From 2014 to 2018, Tunisia experienced a number of strikes organised by its largest trade union. There was also a significant fall in its foreign exchange rate.", "q": "Identify two of the three resource allocation decisions.", "ans": ["What to produce", "How to produce"], "concept": "MS: what to produce, how to produce, who to produce for." },
  { "id": "SBa_W21_5a", "case": "The US operates a mainly market economic system. Life expectancy in the US fell in 2017, for the third year in a row. Although the US has a high GDP per head, it also has a high level of income inequality. The poor benefited from the US's low and stable inflation rate. The government's supply-side policy measures were partly responsible for reducing inflationary pressure.", "q": "Identify two ways a government could reduce income inequality.", "ans": ["Progressive taxation", "State benefits / minimum wage"], "concept": "MS: progressive taxation, state benefits, education, healthcare, equal pay, minimum wage." },
  // --- W22 ---
  { "id": "SBa_W22_2a", "case": "Australia has recruited teachers from Canada, the UK and the US. Most of these teachers specialise in a single subject.", "q": "Define opportunity cost.", "ans": ["Next best alternative forgone", "choice sacrificed"], "concept": "MS: (next) best alternative (1) forgone/sacrificed (1)." },
  { "id": "SBa_W22_3a", "case": "In 2019, Russia had an unemployment rate of 4.6%. Russia experienced full employment in the past.", "q": "Define full employment.", "ans": ["Lowest unemployment possible", "job vacancies match number unemployed"], "concept": "MS: lowest unemployment / job vacancies matching unemployed (2)." },
  { "id": "SBa_W22_4a", "case": "Wood is in inelastic supply. Wood can be supplied in all economic systems. Public goods are not supplied in a market economic system.", "q": "Define inelastic supply.", "ans": ["Quantity supplied changes by smaller percentage than price", "PES less than 1"], "concept": "MS: supply changes by smaller % than price (2) or PES<1 (1)." },
  { "id": "SBa_W22_5a", "case": "In 2019, the US government imposed some methods of protection to reduce imports from Mexico.", "q": "Identify two methods of protection.", "ans": ["Tariffs (tax on imports)", "Quotas (limit on imports)"], "concept": "MS: tariffs, quotas, subsidies, embargo." },
  // --- W23 ---
  { "id": "SBa_W23_2a", "case": "Botswana uses both capital goods and labour in its diamond mining industry. The country had an average economic growth rate of 3.8% between 2015 and 2019.", "q": "Define, with an example, a capital good.", "ans": ["Good used to produce another good or service / human-made good used for production", "e.g. a machine"], "concept": "MS: Definition (1) + example (1). Accept: machinery, equipment, factory." },
  { "id": "SBa_W23_3a", "case": "In 2020, some firms in Suriname stopped production because they could not cover their variable costs, as well as some of their fixed costs.", "q": "Define, with an example, a fixed cost.", "ans": ["Cost that does not change with output / cost paid even when output is zero", "e.g. rent"], "concept": "MS: Definition (1) + example (1). Accept: machinery, electricity, wages (if justified)." },
  { "id": "SBa_W23_4a", "case": "In the US, the supply of meat from emus is price-elastic. US farmers have switched to keeping other livestock.", "q": "Define elastic supply.", "ans": ["Percentage change in quantity supplied greater than percentage change in price", "PES greater than 1"], "concept": "MS: Full def (2) or 'change in supply > change in price' (1) + PES>1 (1)." },
  { "id": "SBa_W23_5a", "case": "In 2020, Singapore experienced a decrease in both its population size and its labour force.", "q": "Identify two benefits of a decrease in a country's population size.", "ans": ["Less pressure on resources", "Fewer dependents"], "concept": "MS: Two from – fewer dependents, less pressure on resources, less food, reduce overpopulation, may increase GDP per head." },
  // --- W24 ---
  { "id": "SBa_W24_2a", "case": "In 2021, the production point on the UK's production possibility curve (PPC) changed. Average wages increased. The average annual wage of a waiter was $23,580 while that of a chief executive of a large commercial bank was $1,617,000. In 2021, the UK government signed free trade agreements, removing import restrictions, with a number of countries.", "q": "Identify two places where a production point could be located on a PPC diagram.", "ans": ["Point on the curve / along the curve", "Point inside the curve / left of the curve"], "concept": "MS: point inside the curve, point on the curve, or point outside the curve (unattainable)." },
  { "id": "SBa_W24_3a", "case": "The central bank of Madagascar intervenes in the country's foreign exchange market. Madagascar has a largely market economic system.", "q": "Define foreign exchange market.", "ans": ["Market where currencies are bought and sold", "exchange of one currency for another"], "concept": "Syllabus 6.3.2: Demand for and supply of currency." },
  { "id": "SBa_W24_4a", "case": "In 2021, there were extensions and contractions in demand for a number of South African products.", "q": "Define an extension in demand.", "ans": ["Increase in quantity demanded due to fall in price", "movement along the demand curve"], "concept": "Syllabus 2.3.2: Movement along demand curve." },
  { "id": "SBa_W24_5a", "case": "Peru's third largest industry is tourism. There are many firms in the Peruvian tourism industry.", "q": "Identify two examples of labour employed in the tourism industry.", "ans": ["Hotel staff", "Tour guides"], "concept": "Accept: waiters, travel agents, pilots, flight attendants, chefs, receptionists." },
  // --- W25 ---
  { "id": "SBa_W25_2a", "case": "Some markets in Belgium are in equilibrium. The country produces a wide range of goods with different degrees of price elasticity of demand.", "q": "Define market equilibrium.", "ans": ["Where quantity demanded equals quantity supplied", "no excess demand or supply"], "concept": "Syllabus 2.5.1: Equilibrium price and quantity." },
  { "id": "SBa_W25_3a", "case": "A French cosmetics firm merged with an Australian cosmetics firm. The merger will lower average total cost through internal economies of scale.", "q": "Define average total cost.", "ans": ["Total cost divided by output", "TC / quantity produced"], "concept": "Syllabus 3.7.2: ATC = TC ÷ output." },
  { "id": "SBa_W25_4a", "case": "The Federal Reserve has two main aims: maintain price stability and achieve full employment.", "q": "Identify two policy measures a central bank could use to maintain price stability.", "ans": ["Interest rates", "Open market operations"], "concept": "Monetary policy tools: interest rates, money supply, reserve requirements." },
  { "id": "SBa_W25_5a", "case": "Some countries engage in dumping by selling their products at less than cost price in Cambodia.", "q": "Identify two motives for a firm dumping some of its products in a foreign market.", "ans": ["Sell excess supply", "Gain market share / drive out competition"], "concept": "Dumping: selling below cost to capture market / dispose surplus." },
  // --- S21 ---
  { "id": "SBa_S21_2a", "case": "Nearly one million people in Cairo live in crowded, unhealthy housing. One reason is unemployment. Other citizens live in luxury.", "q": "Identify two basic necessities, other than housing.", "ans": ["Food", "Healthcare / medicine"], "concept": "Basic necessities: food, shelter, clothing, healthcare." },
  { "id": "SBa_S21_3a", "case": "Consumers in Uruguay are eating more processed foods. Factors of production, including enterprise, have responded.", "q": "Define enterprise.", "ans": ["Taking risks / organising production", "combining factors of production"], "concept": "Syllabus 1.2.1: Enterprise – risk-taking, decision-making." },
  { "id": "SBa_S21_4a", "case": "Turkey's birth rate is falling. Improvements in the quality of labour and MNCs operating in Turkey may help avoid a recession.", "q": "Define birth rate.", "ans": ["Number of births per thousand of population", "per year"], "concept": "Syllabus 5.3.1: Births per 1000 per year." },
  { "id": "SBa_S21_5a", "case": "The money supply in Bangladesh increased every year from 2010 to 2018. Changes in the money supply affect macroeconomic aims.", "q": "Identify two functions of money.", "ans": ["Medium of exchange", "Store of value"], "concept": "Syllabus 3.1.1: Medium of exchange, store of value, unit of account." },
  // --- S23 ---
  { "id": "SBa_S23_2a", "case": "In 2020, the largest Thai commercial bank merged with a smaller commercial Thai bank. It was expected that the merger would affect the price charged for bank services and the amount that would be lent. Thai commercial banks operate in the private sector.", "q": "Identify two influences, other than price, on a customer's choice of bank.", "ans": ["Location", "Services provided / amount willing to lend"], "concept": "MS: services provided, amount willing to lend, location, online facilities, interest paid, reputation, etc." },
  { "id": "SBa_S23_3a", "case": "Canada's private sector firms have a number of different objectives. There has been increased investment with firms buying more capital goods.", "q": "Identify two objectives of private sector firms.", "ans": ["Profit maximisation", "Growth / market share"], "concept": "Syllabus 3.7.5: Survival, profit, growth, social welfare." },
  { "id": "SBa_S23_4a", "case": "In 2020, Australia had a high national minimum wage (NMW). The NMW is received by some people who work on Australian dairy farms. Australia produces milk and soft drinks.", "q": "Identify two reasons why a government may set an NMW.", "ans": ["To reduce poverty / raise living standards", "To ensure fair wages / prevent exploitation"], "concept": "MS: raise wages, reduce poverty, reduce inequality, correct market failure, encourage job seeking." },
  { "id": "SBa_S23_5a", "case": "In 2019, China's economic growth rate was 6.1% and Chinese households increased their spending. China exported more despite a rise in tariffs on some of its products. For example, the US imposed higher tariffs on the imports of Chinese tea and coffee.", "q": "Identify the opportunity cost of households spending their income and the opportunity cost of Chinese firms exporting goods and services.", "ans": ["Saving (forgone)", "Selling the products at home / domestic consumption"], "concept": "MS: Saving (1) selling at home / consuming the products (1)." },
  // --- S24 ---
  { "id": "SBa_S24_2a", "case": "In 2020, wages paid to Mexican workers, including those in the primary sector, fell. This contributed to a 9% rise in poverty.", "q": "Identify two possible opportunity costs of producing primary sector products.", "ans": ["Resources not used for manufacturing", "Resources not used for services"], "concept": "Opportunity cost: what else could have been produced." },
  { "id": "SBa_S24_3a", "case": "South America has millions of microeconomic decision-makers. During a pandemic, schools stayed closed longer than anywhere else.", "q": "Identify the difference between microeconomics and macroeconomics.", "ans": ["Micro: individual markets / firms / households", "Macro: whole economy / GDP / inflation"], "concept": "Micro = individual units; Macro = economy as a whole." },
  { "id": "SBa_S24_4a", "case": "In 2020, the Tajik government was concerned the economy might experience a recession which could cause a fall in tax revenue.", "q": "Identify two reasons why tax revenue is likely to fall during a recession.", "ans": ["Lower incomes / less income tax", "Lower profits / less corporation tax"], "concept": "Recession: fall in incomes, profits, spending → less tax revenue." },
  { "id": "SBa_S24_5a", "case": "Free goods and economic goods are consumed in Poland. In 2020, demand for both economic goods and factors of production increased.", "q": "Identify two free goods.", "ans": ["Air", "Sunlight"], "concept": "Free goods: no opportunity cost, naturally abundant." },
  // --- S25 ---
  { "id": "SBa_S25_2a", "case": "The world's four largest accountancy firms experienced a decline in demand. One cause was a decline in mergers in other industries.", "q": "Identify two advantages a firm may gain from merging with another firm.", "ans": ["Economies of scale", "Increased market share / power"], "concept": "Merger benefits: economies of scale, market power, diversification." },
  { "id": "SBa_S25_3a", "case": "In 2022, Paraguay's production possibility curve (PPC) shifted to the right. Paraguay has a mixed economic system.", "q": "Identify what is measured on the axes of a production possibility curve.", "ans": ["Quantity of one good / output", "Quantity of another good / output"], "concept": "PPC axes: two different goods or categories of output." },
  { "id": "SBa_S25_4a", "case": "More than a quarter of a million workers, including doctors, left Sri Lanka to work in other countries. Largely due to economic problems including 50% inflation.", "q": "Identify two types of unemployment.", "ans": ["Frictional (between jobs)", "Structural (skills mismatch)"], "concept": "Syllabus 4.7.4: Frictional, structural, cyclical." },
  { "id": "SBa_S25_5a", "case": "The Chinese Government aimed for 5% economic growth. Higher output would be caused mainly by an increase in household spending.", "q": "Identify two influences on household spending.", "ans": ["Income", "Interest rates / confidence"], "concept": "Syllabus 3.2.1: Income, interest rate, confidence." },
  // --- M21 ---
  { "id": "SBa_M21_2a", "case": "India has experienced a relatively high economic growth rate. This growth has been driven by increases in government spending and exports.", "q": "Define economic growth.", "ans": ["Increase in country's output / real GDP", "over time"], "concept": "MS: Increase in output (2) or real GDP over time (1+1)." },
  { "id": "SBa_M21_3a", "case": "In the Netherlands in 2018, there were 1.3 bicycles per person. Land is scarce in city centres, where most cycling takes place. Demand for bikes in the Netherlands is price-inelastic.", "q": "Identify one difference between land and labour.", "ans": ["Land is a natural resource", "Labour is a human resource / people"], "concept": "MS: Land is natural resource (1) labour is human resource / people (1)." },
  { "id": "SBa_M21_4a", "case": "Half of Egyptian men smoke. The Egyptian government has increased the tax on cigarettes.", "q": "Identify two qualities of a good tax.", "ans": ["Equitable / fair", "Convenient / easy to collect"], "concept": "MS: equity, convenience, certainty, economy." },
  { "id": "SBa_M21_5a", "case": "Sweden has a mixed economic system. In 2018, it was operating at a point inside its production possibility curve.", "q": "Define a mixed economic system.", "ans": ["Combination of market and government", "private and public sector"], "concept": "Syllabus 2.11.1: Mix of market and government." },
  // --- M22 ---
  { "id": "SBa_M22_2a", "case": "South Africa experienced a recession and unemployment rate of 29%. Only a small proportion was frictional unemployment.", "q": "Define frictional unemployment.", "ans": ["Workers in between jobs", "temporarily unemployed while searching"], "concept": "Syllabus 4.7.4: Short-term, between jobs." },
  { "id": "SBa_M22_3a", "case": "Most New Zealand firms are relatively small and most do not experience diseconomies of scale. New Zealand was the first to introduce a national minimum wage.", "q": "Define diseconomies of scale.", "ans": ["Rise in average cost as output increases", "inefficiency from being too large"], "concept": "Syllabus 3.5.5: Average cost rises with scale." },
  { "id": "SBa_M22_4a", "case": "Botswana's net migration varies. In 2019, Botswana had net immigration. Since 2010, unemployment has averaged 18%.", "q": "Identify two reasons why immigration may increase.", "ans": ["Higher wages / better jobs", "Better living standards / escape conflict"], "concept": "Pull factors: jobs, wages, safety, opportunities." },
  { "id": "SBa_M22_5a", "case": "The economic problem means that countries have to decide what to produce. Ghana uses much of its agricultural land to grow cocoa.", "q": "Define the economic problem.", "ans": ["Unlimited wants and finite resources", "scarcity"], "concept": "Syllabus 1.1.1: Scarcity – limited resources, unlimited wants." },
  // --- M23 ---
  { "id": "SBa_M23_2a", "case": "Vietnam has a high number of female entrepreneurs. Some firms compete with foreign MNCs and public sector firms.", "q": "Identify two reasons why people become entrepreneurs.", "ans": ["Profit motive / be own boss", "Spot a business opportunity"], "concept": "Entrepreneurs: profit, independence, opportunity." },
  { "id": "SBa_M23_3a", "case": "India became the world's largest producer of sugar. The Indian government sets a minimum price for sugar cane and subsidises the export of sugar.", "q": "Define a minimum price.", "ans": ["Price floor set by government", "price cannot fall below this level"], "concept": "Syllabus 2.11.2: Price floor – minimum allowed." },
  { "id": "SBa_M23_4a", "case": "By 2020, 40% of Turkish doctors were women. Over this period, labour productivity increased. Turkey experienced advances in technology.", "q": "Identify two causes of an increase in labour productivity.", "ans": ["Training / education", "Better technology / capital"], "concept": "Productivity: skills, technology, capital, division of labour." },
  { "id": "SBa_M23_5a", "case": "Serbia is the world's second largest producer of raspberries, a product with elastic demand. Consumers experience the economic problem when buying raspberries.", "q": "Identify two determinants of price elasticity of demand.", "ans": ["Availability of substitutes", "Proportion of income / necessity"], "concept": "Syllabus 2.7.3: Substitutes, necessity, income proportion." },
  // --- M24 ---
  { "id": "SBa_M24_2a", "case": "South Korea's population has declined. The government has used tax revenue to give cash incentives to couples to have more children.", "q": "Identify two benefits people may gain from a good education.", "ans": ["Higher income / better job", "Better health / life expectancy"], "concept": "Education: earnings, health, productivity." },
  { "id": "SBa_M24_3a", "case": "Some firms in Monaco have experienced external growth. Firms in Monaco pay high wages. Workers benefit from fiscal policy.", "q": "Define external growth of firms.", "ans": ["Growth through merger / takeover", "acquiring other firms"], "concept": "Syllabus 3.5.4: External = merger, not internal expansion." },
  { "id": "SBa_M24_4a", "case": "In 2021, the Suez Canal was blocked. This affected some firms' profits and caused a shortage in a number of products.", "q": "Define a shortage.", "ans": ["Demand exceeds supply", "excess demand"], "concept": "Syllabus 2.5.2: Quantity demanded > quantity supplied." },
  { "id": "SBa_M24_5a", "case": "New Zealand has a low unemployment rate and a surplus of imports over exports. In 2022, it banned everyone born after 2008 from buying cigarettes.", "q": "Define unemployment rate.", "ans": ["Percentage of labour force unemployed", "unemployed / labour force × 100"], "concept": "Syllabus 4.7.3: Unemployed ÷ labour force × 100." },
  // --- M25 ---
  { "id": "SBa_M25_2a", "case": "South Korea makes use of both economic goods and free goods. Its output includes products with both elastic and inelastic supply.", "q": "Identify a difference between economic goods and free goods.", "ans": ["Economic goods have opportunity cost", "Free goods have no opportunity cost"], "concept": "Economic = scarce, opportunity cost. Free = abundant, no OC." },
  { "id": "SBa_M25_3a", "case": "Estonia's factors of production are employed in education, building and clothing. In 2022, the country experienced a shortage of teachers.", "q": "Define factor of production.", "ans": ["Resource used to produce goods and services", "land, labour, capital or enterprise"], "concept": "Syllabus 1.2.1: Land, labour, capital, enterprise." },
  { "id": "SBa_M25_4a", "case": "Nigeria had a high unemployment rate of 33% which created a number of costs. Its high inflation rate of 22% had several effects on firms.", "q": "Identify two costs of unemployment.", "ans": ["Loss of income for individuals", "Lower GDP / lost output"], "concept": "Costs: lost income, lower output, social problems." },
  { "id": "SBa_M25_5a", "case": "Finland usually has a higher value of exports than imports. It has a strong commercial banking sector.", "q": "Identify a difference between an export and an import.", "ans": ["Export: good sold to another country", "Import: good bought from another country"], "concept": "Export = sold abroad. Import = bought from abroad." },

  // ═══════════════════════════════════════════════════════════════
  // SYLLABUS 1: The basic economic problem
  // ═══════════════════════════════════════════════════════════════
  { "id": "SBa_s1_scarcity", "case": "Kenya faces difficult choices about how to use its land. It has limited fertile soil but must produce food, grow cash crops for export, and provide space for housing and industry. The government has to decide what to produce and who to produce for.", "q": "Define the basic economic problem.", "ans": ["Unlimited wants and finite resources", "scarcity of resources"], "concept": "Syllabus 1.1.1: Scarcity forces choice." },
  { "id": "SBa_s1_opportunity_cost", "case": "A student in Egypt chose to study economics instead of working part-time in a shop. Her family needed the extra income but supported her decision to focus on exams. She gave up her wages to gain qualifications.", "q": "Define opportunity cost.", "ans": ["Next best alternative forgone", "choice sacrificed"], "concept": "MS: (next) best alternative (1) forgone/sacrificed (1)." },
  { "id": "SBa_s1_PPC", "case": "Chile can produce copper or wine using its resources. In 2020, it produced more copper and less wine. The country's production possibility curve shows the maximum combinations it could produce with its existing resources and technology.", "q": "Define a production possibility curve.", "ans": ["Shows maximum combination of goods an economy can produce", "with given resources and technology"], "concept": "Syllabus 1.4.1: Boundary of attainable output." },
  { "id": "SBa_s1_factors", "case": "A textile firm in Bangladesh uses land for its factory, employs workers to operate machinery, and has managers who organise production. The firm must decide how to combine these resources to produce clothing for export.", "q": "Identify two factors of production.", "ans": ["Labour (human effort)", "Capital (man-made aids to production)"], "concept": "Syllabus 1.2.1: Land, labour, capital, enterprise." },
  { "id": "SBa_s1_land", "case": "A coffee farm in Colombia uses fertile soil, rainfall and mineral deposits. These natural resources are used to grow coffee beans. The reward for land is rent.", "q": "Define, with an example, land.", "ans": ["Natural resources used in production", "e.g. soil / minerals / water"], "concept": "Syllabus 1.2.1: Land – natural factor, reward = rent." },
  { "id": "SBa_s1_labour", "case": "A factory in Vietnam employs hundreds of workers to assemble electronics. These workers provide their physical and mental effort. The reward for labour is wages.", "q": "Define, with an example, labour.", "ans": ["Human effort in production / physical and mental work", "e.g. factory workers / teachers"], "concept": "Syllabus 1.2.1: Labour – human factor, reward = wages." },
  { "id": "SBa_s1_economic_good", "case": "In Jordan, most goods such as water, food and fuel have an opportunity cost. They are scarce and require resources to produce. The government must decide how to allocate these goods.", "q": "Define an economic good.", "ans": ["Good that has an opportunity cost", "scarce / requires resources to produce"], "concept": "Syllabus 1.1.2: Economic vs free goods." },

  // ═══════════════════════════════════════════════════════════════
  // SYLLABUS 2: The allocation of resources
  // ═══════════════════════════════════════════════════════════════
  { "id": "SBa_s2_demand", "case": "In Norway, demand for electric cars increased when the government offered subsidies. Consumers were willing and able to buy more vehicles at each price level. The number of electric cars on the road tripled between 2019 and 2022.", "q": "Define demand.", "ans": ["Quantity of a good consumers are willing and able to buy", "at a given price"], "concept": "Syllabus 2.3.1: Willing, able, at a price." },
  { "id": "SBa_s2_supply", "case": "In 2022, wheat prices rose in Ukraine. Farmers responded by planting more wheat and supplying more to the market. Some farmers switched from growing sunflowers to wheat because of the higher price they could receive.", "q": "Define supply.", "ans": ["Quantity of a good producers are willing and able to supply", "at a given price"], "concept": "Syllabus 2.4.1: Willing, able, at a price." },
  { "id": "SBa_s2_extension_demand", "case": "In Indonesia, a fall in the price of motorcycles led to more motorcycles being sold. The movement along the demand curve showed consumers buying more at the lower price. Sales increased by 15% in one year.", "q": "Define an extension in demand.", "ans": ["Increase in quantity demanded due to fall in price", "movement along the demand curve"], "concept": "Syllabus 2.3.2: Movement along curve." },
  { "id": "SBa_s2_contraction_demand", "case": "In Thailand, a rise in the price of rice led to fewer bags being sold. Consumers bought less at the higher price. This movement along the demand curve is called a contraction in demand.", "q": "Define a contraction in demand.", "ans": ["Decrease in quantity demanded due to rise in price", "movement along the demand curve"], "concept": "Syllabus 2.3.2: Extensions and contractions." },
  { "id": "SBa_s2_contraction_supply", "case": "In Germany, when the price of solar panels fell, manufacturers supplied fewer panels to the market. The movement along the supply curve reflected producers reducing output at the lower price. Some firms cut production or left the market.", "q": "Define a contraction in supply.", "ans": ["Decrease in quantity supplied due to fall in price", "movement along the supply curve"], "concept": "Syllabus 2.4.2: Movement along curve." },
  { "id": "SBa_s2_equilibrium", "case": "In the market for rice in Thailand, the price settled at a level where the quantity farmers wished to supply exactly matched the quantity consumers wished to buy. There was no excess demand or excess supply at this price.", "q": "Define market equilibrium.", "ans": ["Where quantity demanded equals quantity supplied", "no excess demand or supply"], "concept": "Syllabus 2.5.1: Equilibrium price and quantity." },
  { "id": "SBa_s2_surplus", "case": "In 2023, the price of wheat in Australia was set above the equilibrium level. At this price, the quantity supplied exceeded the quantity demanded. This market disequilibrium created a surplus of wheat.", "q": "Define a surplus.", "ans": ["Supply exceeds demand", "excess supply"], "concept": "Syllabus 2.5.2: Disequilibrium – supply exceeding demand." },
  { "id": "SBa_s2_market_system", "case": "In many countries, resources are allocated through the price mechanism. Buyers and sellers interact freely and prices signal what to produce, how to produce and for whom. The government plays a limited role in this system.", "q": "Define a market economic system.", "ans": ["Resources allocated by price mechanism", "decisions by buyers and sellers / limited government"], "concept": "Syllabus 2.9.1: Market system." },
  { "id": "SBa_s2_PED", "case": "In Singapore, demand for luxury handbags fell sharply when prices rose by 20%. Sales dropped by 35%. Producers of these goods were concerned about the responsiveness of their customers to price changes.", "q": "Define price elasticity of demand.", "ans": ["Responsiveness of quantity demanded to a change in price", "percentage change in quantity demanded / percentage change in price"], "concept": "Syllabus 2.7.1: PED formula." },
  { "id": "SBa_s2_market_failure", "case": "In Pakistan, pollution from leather tanneries affected local residents and damaged farmland. The market price of leather did not include the cost of this damage. The government considered regulation to correct the misallocation of resources.", "q": "Define market failure.", "ans": ["Misallocation of resources by the market", "market does not achieve allocative efficiency"], "concept": "Syllabus 2.10.1: Market fails to allocate efficiently." },
  { "id": "SBa_s2_ident_causes_market_failure", "case": "Street lighting is not provided by the market. A monopoly charges high prices. Polluting factories impose costs on society. There are several causes of market failure.", "q": "Identify two causes of market failure.", "ans": ["Public goods / merit goods", "External costs / abuse of monopoly power"], "concept": "Syllabus 2.10.2: Public goods, externalities, monopoly." },
  { "id": "SBa_s2_public_good", "case": "In many countries, street lighting is provided by the government. Private firms do not supply it because they cannot exclude people who do not pay from using it. Once installed, one person's use does not reduce the amount available for others.", "q": "Define, with an example, a public good.", "ans": ["Non-excludable and non-rival", "e.g. street lighting / national defence"], "concept": "Syllabus 2.10.2: Non-excludability, non-rivalry." },
  { "id": "SBa_s2_external_cost", "case": "A cement factory in Vietnam discharged waste into a nearby river. Local fishermen lost their livelihood and residents suffered from contaminated water. The factory did not have to pay for these costs imposed on third parties.", "q": "Define, with an example, an external cost.", "ans": ["Cost imposed on third parties not borne by the producer", "e.g. pollution / noise"], "concept": "Syllabus 2.10.2: Third parties / society." },
  { "id": "SBa_s2_merit_good", "case": "The Nigerian government subsidises education and healthcare. These goods have benefits to society beyond the private benefit to the consumer. The market would under-provide them without government intervention.", "q": "Define, with an example, a merit good.", "ans": ["Good with external benefits / social benefits exceed private benefits", "e.g. education / healthcare"], "concept": "Syllabus 2.10.2: Merit goods – under-consumed." },
  { "id": "SBa_s2_demerit_good", "case": "The Egyptian government taxes cigarettes heavily. Cigarettes have external costs to society such as healthcare costs and lost productivity. Without intervention, the market would over-provide such goods.", "q": "Define, with an example, a demerit good.", "ans": ["Good with external costs / social costs exceed private costs", "e.g. cigarettes / alcohol"], "concept": "Syllabus 2.10.2: Demerit goods – over-consumed." },
  { "id": "SBa_s2_external_benefit", "case": "A firm in Kenya trained its workers in new skills. When workers left for other jobs, they took these skills with them. Other firms benefited from this training but did not pay for it.", "q": "Define, with an example, an external benefit.", "ans": ["Benefit to third parties not received by the producer/consumer", "e.g. training / vaccination"], "concept": "Syllabus 2.10.2: External benefits." },
  { "id": "SBa_s2_protection", "case": "In 2019, the Indian government raised tariffs on imports of electronic goods to protect domestic producers. It also limited the quantity of some textiles that could be imported each year. These measures were designed to reduce competition from abroad.", "q": "Identify two methods of protection.", "ans": ["Tariffs (tax on imports)", "Quotas (limit on imports)"], "concept": "Syllabus 6.2.4: Tariffs, quotas, subsidies, embargoes." },
  { "id": "SBa_s2_maximum_price", "case": "The Venezuelan government set a maximum price for basic food staples. Sellers could not legally charge above this price. The aim was to make food affordable for the poor during high inflation.", "q": "Define a maximum price.", "ans": ["Price ceiling set by government", "price cannot rise above this level"], "concept": "Syllabus 2.11.2: Maximum price – ceiling." },
  { "id": "SBa_s2_ident_reasons_protection", "case": "Some developing countries protect their infant industries from foreign competition. Others use protection to prevent dumping. Governments give various reasons for imposing tariffs and quotas.", "q": "Identify two reasons why a government may impose protection.", "ans": ["Protect infant industry", "Prevent dumping / protect declining industry"], "concept": "Syllabus 6.2.5: Infant industry, dumping, strategic." },

  // ═══════════════════════════════════════════════════════════════
  // SYLLABUS 3: Microeconomic decision makers
  // ═══════════════════════════════════════════════════════════════
  { "id": "SBa_s3_consumption", "case": "In the Philippines, household spending rose when interest rates fell and consumer confidence increased. Families spent more on food, transport and household goods. Consumption accounts for about 70% of the country's GDP.", "q": "Define, with an example, consumption.", "ans": ["Spending by households on goods and services", "e.g. food / clothing / transport"], "concept": "Distinguish from investment." },
  { "id": "SBa_s3_investment", "case": "A South Korean electronics firm spent $2 billion on new factories and machinery in 2022. This added to the country's capital stock. The firm expected the investment to increase its future output and profits.", "q": "Define, with an example, investment.", "ans": ["Spending on capital goods / adding to capital stock", "e.g. machinery / buildings"], "concept": "Capital formation." },
  { "id": "SBa_s3_trade_union", "case": "Workers at a factory in Poland joined a trade union. The union negotiated with the employer for higher wages and better working conditions. The employer agreed to pay rises after collective bargaining.", "q": "Define a trade union.", "ans": ["Organisation of workers", "collective bargaining for wages and conditions"], "concept": "Syllabus 3.4.1: Collective bargaining." },
  { "id": "SBa_s3_variable_cost", "case": "A bakery in France increased its output of bread. The cost of flour, yeast and the wages of extra bakers all rose. These costs varied directly with the number of loaves produced.", "q": "Define, with an example, a variable cost.", "ans": ["Cost that changes with output", "e.g. raw materials / labour"], "concept": "Syllabus 3.7.1: FC vs VC." },
  { "id": "SBa_s3_monopoly", "case": "In some countries, one firm supplies all the electricity to households. New firms find it difficult to enter the market because of the high costs of building power stations and transmission networks. There are no close substitutes.", "q": "Define a monopoly.", "ans": ["Single seller / one firm dominates the market", "barriers to entry"], "concept": "Syllabus 3.8.2: Single seller." },
  { "id": "SBa_s3_division_labour", "case": "At a car factory in Mexico, each worker on the assembly line performs one specific task. One worker fits doors, another installs seats, and another checks the brakes. This specialisation increased output per worker.", "q": "Define division of labour.", "ans": ["Specialisation of workers on specific tasks", "splitting production into separate jobs"], "concept": "Syllabus 3.3.4: Specialisation at worker level." },
  { "id": "SBa_s3_economies_scale", "case": "A large supermarket chain in the UK had lower average cost per unit than smaller rivals. Buying in bulk and spreading fixed costs over more output reduced the cost of each item sold. Smaller stores could not match these efficiency gains.", "q": "Define economies of scale.", "ans": ["Fall in average cost as output increases", "efficiency gains from larger scale"], "concept": "Syllabus 3.5.5: Internal economies." },
  { "id": "SBa_s3_ident_sectors", "case": "Ethiopia's economy includes coffee farming in the highlands, textile manufacturing in industrial zones, and banking and tourism in the cities. Each sector uses factors of production in different ways.", "q": "Identify two sectors of the economy.", "ans": ["Primary sector (extraction/farming)", "Secondary sector (manufacturing)"], "concept": "Primary, secondary, tertiary." },
  { "id": "SBa_s3_ident_mergers", "case": "Two car manufacturers merged to form a larger company. A soft drink firm acquired a bottling plant. Firms grow through different types of mergers.", "q": "Identify two types of merger.", "ans": ["Horizontal (same industry / competitors)", "Vertical (different stage of production)"], "concept": "Syllabus 3.5.4: Horizontal, vertical, conglomerate." },
  { "id": "SBa_s3_ident_occupation", "case": "A graduate in Kenya chose to work for a bank rather than a school. She considered the salary, location and job security. Wage and non-wage factors affect people's choice of occupation.", "q": "Identify two factors that affect an individual's choice of occupation.", "ans": ["Wage level / salary", "Job satisfaction / working conditions / location"], "concept": "Syllabus 3.3.1: Wage and non-wage factors." },
  { "id": "SBa_s3_ident_saving", "case": "Households in Japan save a high proportion of their income. In other countries, saving rates are lower. The rate of interest and confidence affect how much people save.", "q": "Identify two influences on household saving.", "ans": ["Rate of interest", "Income / confidence about future"], "concept": "Syllabus 3.2.1: Influences on saving." },

  // ═══════════════════════════════════════════════════════════════
  // SYLLABUS 4: Government and the macroeconomy
  // ═══════════════════════════════════════════════════════════════
  { "id": "SBa_s4_inflation", "case": "In Turkey, prices rose by over 60% in 2023. The general price level increased sustainedly and the purchasing power of money fell. The central bank raised interest rates to bring inflation under control.", "q": "Define inflation.", "ans": ["Rise in the general price level", "sustained increase in prices over time"], "concept": "Syllabus 4.8.1: General price level." },
  { "id": "SBa_s4_unemployment", "case": "Spain's unemployment rate rose to 13% during the recession. Many people were willing and able to work and were actively seeking jobs but could not find employment. The government introduced schemes to help the unemployed.", "q": "Define unemployment.", "ans": ["People willing and able to work but not in paid employment", "actively seeking work"], "concept": "Syllabus 4.7.1: Willing, able, seeking." },
  { "id": "SBa_s4_GDP", "case": "Vietnam's economy grew by 5% in 2023. The total value of goods and services produced in the country increased. GDP is used as a measure of the size of the economy.", "q": "Define GDP.", "ans": ["Total value of goods and services produced in an economy", "over a period of time"], "concept": "Syllabus 4.6.1: Real GDP." },
  { "id": "SBa_s4_fiscal", "case": "The UK government raised income tax and cut spending on public services in 2023. These fiscal measures were designed to reduce the budget deficit and influence the level of economic activity.", "q": "Define fiscal policy.", "ans": ["Use of government spending and taxation", "to influence the economy"], "concept": "Syllabus 4.3.7: Tax and spending." },
  { "id": "SBa_s4_monetary", "case": "The European Central Bank raised interest rates in 2023 to reduce inflation. It also influenced the money supply through open market operations. These monetary policy measures affected borrowing and spending in the eurozone.", "q": "Define monetary policy.", "ans": ["Use of interest rates and money supply", "to influence the economy"], "concept": "Syllabus 4.4.1: Interest rates." },
  { "id": "SBa_s4_supply_side", "case": "The Malaysian government invested in vocational training and reduced the rate of corporation tax. It hoped these supply-side policies would increase the economy's productive capacity and raise the long-run growth rate.", "q": "Define supply-side policy.", "ans": ["Policies to increase productive capacity", "e.g. training / deregulation / lower tax"], "concept": "Syllabus 4.5.1: Increase capacity." },
  { "id": "SBa_s4_progressive_tax", "case": "In Denmark, higher earners pay a larger proportion of their income in tax than lower earners. Someone earning €100,000 pays a higher percentage in tax than someone earning €20,000. This is designed to redistribute income.", "q": "Define a progressive tax.", "ans": ["Takes a higher proportion of income from higher earners", "proportion / share / percentage rises with income"], "concept": "Syllabus 4.3.4: Proportion rises with income." },
  { "id": "SBa_s4_regressive_tax", "case": "VAT is the same percentage for all consumers. Low-income households spend a larger proportion of their income on goods subject to VAT. This type of tax takes a higher proportion from lower earners.", "q": "Define a regressive tax.", "ans": ["Takes a higher proportion of income from lower earners", "proportion falls as income rises"], "concept": "Syllabus 4.3.4: Regressive tax." },
  { "id": "SBa_s4_deflation", "case": "Japan experienced falling prices for several years. The general price level decreased sustainedly. Consumers delayed spending in the hope of lower prices in the future.", "q": "Define deflation.", "ans": ["Fall in the general price level", "sustained decrease in prices over time"], "concept": "Syllabus 4.8.1: Deflation." },
  { "id": "SBa_s4_recession", "case": "In 2020, many economies experienced two quarters of falling GDP. Output decreased and unemployment rose. The economy moved to a point inside its production possibility curve.", "q": "Define a recession.", "ans": ["Fall in output / GDP", "two quarters of negative growth / economy inside PPC"], "concept": "Syllabus 4.6.3: Recession." },
  { "id": "SBa_s4_ident_macro_aims", "case": "The Brazilian government has several macroeconomic aims. It wants to maintain low and stable inflation, achieve full employment, and promote sustainable economic growth. These aims sometimes conflict with each other.", "q": "Identify two macroeconomic aims of government.", "ans": ["Low inflation / stable prices", "Full employment / low unemployment"], "concept": "Syllabus 4.2.1: Growth, employment, inflation, BoP, redistribution." },
  { "id": "SBa_s4_ident_inflation_causes", "case": "Zimbabwe experienced very high inflation. One cause was excess demand as the government printed money to finance spending. Another was rising costs as imported fuel and fertiliser became more expensive.", "q": "Identify two causes of inflation.", "ans": ["Demand-pull (excess demand)", "Cost-push (rising costs)"], "concept": "Syllabus 4.8.3: Demand-pull, cost-push." },
  { "id": "SBa_s4_ident_unemployment_types", "case": "In Portugal, unemployment increased when car factories closed. Some workers were temporarily unemployed while searching for new jobs. Others had skills that no longer matched the jobs available in the growing technology sector.", "q": "Identify two types of unemployment.", "ans": ["Frictional (between jobs)", "Structural (skills mismatch)"], "concept": "Syllabus 4.7.4: Frictional, structural, cyclical." },
  { "id": "SBa_s4_ident_supply_side", "case": "The UK government invested in apprenticeships and reduced income tax rates. It hoped these supply-side measures would increase productivity and raise the economy's productive capacity.", "q": "Identify two supply-side policy measures.", "ans": ["Education and training", "Lower direct taxes / deregulation"], "concept": "Syllabus 4.5.2: Training, labour market reforms, tax." },

  // ═══════════════════════════════════════════════════════════════
  // SYLLABUS 5: Economic development
  // ═══════════════════════════════════════════════════════════════
  { "id": "SBa_s5_HDI", "case": "Costa Rica scored well on the Human Development Index. It had high life expectancy, a high level of education, and a reasonable GDP per head. The HDI measures development more broadly than GDP alone.", "q": "Define the Human Development Index.", "ans": ["Measure of development combining income, health and education", "life expectancy, education, GDP per head"], "concept": "Syllabus 5.1.1: HDI components." },
  { "id": "SBa_s5_absolute_poverty", "case": "In Niger, many people live on less than $2 per day. They cannot afford enough food, clean water, shelter or basic healthcare. This level of deprivation is known as absolute poverty.", "q": "Define absolute poverty.", "ans": ["Below minimum level of income for basic needs", "cannot afford food, shelter, clothing"], "concept": "Syllabus 5.2.1: Basic necessities." },
  { "id": "SBa_s5_relative_poverty", "case": "In the UK, some people earn much less than the average income. They cannot afford the standard of living enjoyed by most people in society. They are said to be in relative poverty.", "q": "Define relative poverty.", "ans": ["Income below a proportion of average income", "compared to others in society"], "concept": "Syllabus 5.2.1: Relative to society." },
  { "id": "SBa_s5_death_rate", "case": "Japan has an ageing population. The death rate is the number of deaths per thousand of the population per year. Birth rate and death rate together affect population size.", "q": "Define death rate.", "ans": ["Number of deaths per thousand of population", "per year"], "concept": "Syllabus 5.3.1: Deaths per 1000 per year." },
  { "id": "SBa_s5_ident_population_factors", "case": "Ireland's population grew in the 2010s. The birth rate remained relatively high and there was net immigration as people moved to Ireland for work. Both factors increased the size of the population.", "q": "Identify two factors that affect population growth.", "ans": ["Birth rate", "Net migration"], "concept": "Syllabus 5.3.1: Birth rate, death rate, migration." },
  { "id": "SBa_s5_ident_development_indicators", "case": "Mali had a low literacy rate and poor healthcare. Life expectancy was below 60 years. Economists use these indicators, as well as GDP per head, to measure economic development.", "q": "Identify two indicators of economic development.", "ans": ["Literacy rate / education", "Life expectancy / healthcare"], "concept": "Syllabus 5.1.1: GDP per head, HDI components." },
  { "id": "SBa_s5_ident_causes_poverty", "case": "Many people in rural Pakistan live in poverty. Unemployment is high and wages in agriculture are low. Illness and lack of education make it difficult for families to escape poverty.", "q": "Identify two causes of poverty.", "ans": ["Unemployment / low wages", "Illness / age / lack of education"], "concept": "Syllabus 5.2.2: Unemployment, low wages, illness, age." },
  { "id": "SBa_s5_ident_policies_poverty", "case": "The Brazilian government used several policies to reduce poverty. It raised the minimum wage and increased spending on education. Progressive taxation helped redistribute income to the poor.", "q": "Identify two policies a government could use to alleviate poverty.", "ans": ["Progressive taxation / state benefits", "Improved education / minimum wage"], "concept": "Syllabus 5.2.3: Growth, education, benefits, NMW." },

  // ═══════════════════════════════════════════════════════════════
  // SYLLABUS 6: International trade and globalisation
  // ═══════════════════════════════════════════════════════════════
  { "id": "SBa_s6_specialisation", "case": "Brazil produces mainly coffee, sugar cane and soya. It concentrates on these goods because it has the climate and land to produce them efficiently. Colombia specialises in coffee while Saudi Arabia specialises in oil.", "q": "Define specialisation.", "ans": ["Producing a narrow range of goods", "concentrating on what one does best"], "concept": "Syllabus 6.1.1: National specialisation." },
  { "id": "SBa_s6_export", "case": "Singapore increased its exports of electronics and financial services in 2023. Goods and services sold to other countries earn foreign exchange. Exports are a major source of Singapore's income.", "q": "Define an export.", "ans": ["Good or service sold to another country", "sold abroad"], "concept": "Syllabus 6.2.3: Trade flows." },
  { "id": "SBa_s6_import", "case": "Nigeria bought more cars, machinery and refined oil from abroad in 2023. These goods and services purchased from other countries are known as imports. A rise in imports can worsen the current account balance.", "q": "Define an import.", "ans": ["Good or service bought from another country", "purchased from abroad"], "concept": "Trade flows." },
  { "id": "SBa_s6_subsidy", "case": "The EU government paid farmers a subsidy for each hectare of wheat they grew. This payment encouraged farmers to produce more. Subsidies can be used to support industries or achieve policy aims.", "q": "Define, with an example, a subsidy.", "ans": ["Payment by government to producers", "e.g. grants to farmers"], "concept": "Definition (1) + example (1)." },
  { "id": "SBa_s6_tariff", "case": "In 2023, a country imposed a tax of 25% on imported cars. This tariff made imported cars more expensive and protected domestic producers. The tax had to be paid when the cars entered the country.", "q": "Define, with an example, a tariff.", "ans": ["Tax on imports / duty on imported goods", "e.g. tax on cars from abroad"], "concept": "Definition (1) + example (1)." },
  { "id": "SBa_s6_exchange_rate", "case": "In 2023, the US dollar strengthened against the Japanese yen. One dollar could buy more yen than before. The foreign exchange rate is the price at which one currency can be exchanged for another.", "q": "Define a foreign exchange rate.", "ans": ["Price of one currency in terms of another", "rate at which currencies are exchanged"], "concept": "Syllabus 6.3.1: Price of currency." },
  { "id": "SBa_s6_globalisation", "case": "Goods, services, capital and labour now move more freely across borders than in the past. Companies produce in several countries and sell worldwide. This growing integration of economies is known as globalisation.", "q": "Define globalisation.", "ans": ["Growing integration of economies", "increased trade and movement of capital/labour"], "concept": "Syllabus 6.2.1: Integration of economies." },
  { "id": "SBa_s6_MNC", "case": "A car manufacturer has factories in Germany, Mexico and China. It sells its products in over 150 countries. This multinational company operates and produces in more than one country.", "q": "Define a multinational company.", "ans": ["Company that operates in more than one country", "produces in multiple countries"], "concept": "Syllabus 6.2.2: MNC definition." },
  { "id": "SBa_s6_ident_BoP", "case": "Argentina had a deficit on its current account in 2023. The value of imported goods exceeded the value of exported goods. The current account also includes trade in services and flows of income.", "q": "Identify two components of the current account.", "ans": ["Trade in goods (visible balance)", "Trade in services"], "concept": "Syllabus 6.4.1: Goods, services, primary income, secondary income." },
  { "id": "SBa_s6_ident_trade_benefits", "case": "Countries that trade internationally can gain from specialisation. Consumers have access to a wider range of products. Competition from imports may also help to keep prices down.", "q": "Identify two benefits of international trade.", "ans": ["Greater choice of goods", "Lower prices / competition"], "concept": "Syllabus 6.2.3: Specialisation, economies of scale." },
  { "id": "SBa_s6_ident_MNC_benefits", "case": "A multinational company built a factory in Romania. It employed 2,000 local workers and invested €500 million in the site. The company also brought new technology and training to the region.", "q": "Identify two benefits of multinational companies.", "ans": ["Create employment", "Bring capital / investment"], "concept": "Syllabus 6.2.2: Jobs, investment, technology." },

  // ═══════════════════════════════════════════════════════════════
  // ADDITIONAL (productivity, market, central bank, etc.)
  // ═══════════════════════════════════════════════════════════════
  { "id": "SBa_add_productivity", "case": "A factory in South Korea installed new machinery. Output per worker increased by 20%. The firm produced more goods with the same number of workers. Productivity is a key determinant of a country's living standards.", "q": "Define productivity.", "ans": ["Output per unit of input", "output per worker / efficiency of production"], "concept": "Syllabus 3.6.3: Output per factor." },
  { "id": "SBa_add_market", "case": "In many towns, buyers and sellers meet to exchange fruit and vegetables. There are also markets for shares, foreign exchange and labour. A market exists wherever buyers and sellers come together to trade.", "q": "Define, with an example, a market.", "ans": ["Where buyers and sellers meet to exchange goods and services", "e.g. stock market / local market"], "concept": "Definition (1) + example (1)." },
  { "id": "SBa_add_central_bank", "case": "The Bank of England sets interest rates to control inflation. It also supervises commercial banks and acts as lender of last resort. The central bank has several important functions in the economy.", "q": "Identify two functions of a central bank.", "ans": ["Monetary policy (interest rates)", "Regulation of commercial banks"], "concept": "Syllabus 3.1.2: Currency, banks, policy." },
  { "id": "SBa_add_fiscal_measures", "case": "To reduce its budget deficit, the Greek government raised VAT and cut spending on public sector wages. These fiscal policy measures were designed to influence the level of economic activity and government revenue.", "q": "Identify two fiscal policy measures.", "ans": ["Change in government spending", "Change in taxation"], "concept": "Syllabus 4.3.8: Spending and tax." },
  { "id": "SBa_add_monetary_tools", "case": "To reduce inflation, the central bank raised the base interest rate. It also sold government bonds to reduce the money supply. These monetary policy tools affect the cost of borrowing and spending.", "q": "Identify two monetary policy tools.", "ans": ["Interest rates", "Open market operations"], "concept": "Syllabus 4.4.2: Interest rates, money supply." },
  { "id": "SBa_add_economic_growth", "case": "Indonesia's economy grew by 5% in 2023. Investment in new factories and technology increased the country's productive capacity. An expansion in the labour force also contributed to higher output.", "q": "Identify two causes of economic growth.", "ans": ["Increase in factors of production", "Increase in productivity"], "concept": "Syllabus 4.6.4: Investment, technology, factors." },
];
